  INFO root [0x00002e40] [2018-05-27 11:29:53,535] - 
  INFO root [0x00002e40] [2018-05-27 11:29:53,591] - -----------------------------------------------------------------------------------------


  INFO root [0x00002e40] [2018-05-27 11:29:54,643] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002e40] [2018-05-27 11:29:54,644] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002e40] [2018-05-27 11:29:54,644] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002e40] [2018-05-27 11:29:55,472] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00002e40] [2018-05-27 11:29:55,584] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00002e40] [2018-05-27 11:29:55,587] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50642 )
  INFO root [0x00002e40] [2018-05-27 11:29:55,588] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50642, SOMAXCONN=128.
  INFO root [0x00002e40] [2018-05-27 11:29:55,588] - server-configs:
  INFO root [0x00002e40] [2018-05-27 11:29:55,588] - 	gameUpdateHertz : 10
  INFO root [0x00002e40] [2018-05-27 11:29:55,588] - 	entryScriptFile : kbemain
  INFO root [0x00002e40] [2018-05-27 11:29:55,589] - 	internalAddr : 192.168.0.104:50642
  INFO root [0x00002e40] [2018-05-27 11:29:55,589] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00002e40] [2018-05-27 11:29:55,589] - 	componentID : 7001
  INFO root [0x00002e40] [2018-05-27 11:29:56,387] - Components::findLogger: found logger, addr:192.168.0.104:50629
  INFO root [0x00002e40] [2018-05-27 11:29:56,388] - Components::addComponent: reset orderLog, uid=4945!
  INFO root [0x00002e40] [2018-05-27 11:29:56,389] - Components::addComponent[logger], uid=4945, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002e40] [2018-05-27 11:29:57,218] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 4945. PID: 11944 ----
  INFO root [0x00002e40] [2018-05-27 11:29:57,219] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002e40] [2018-05-27 11:29:57,462] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002e40] [2018-05-27 11:29:57,565] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00000cc0] [2018-05-27 11:30:04,649] - 
  INFO root [0x00000cc0] [2018-05-27 11:30:04,655] - -----------------------------------------------------------------------------------------


  INFO root [0x00000cc0] [2018-05-27 11:30:04,656] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000cc0] [2018-05-27 11:30:04,656] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000cc0] [2018-05-27 11:30:04,656] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000cc0] [2018-05-27 11:30:04,665] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00000cc0] [2018-05-27 11:30:04,665] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00000cc0] [2018-05-27 11:30:04,667] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50649 )
  INFO root [0x00000cc0] [2018-05-27 11:30:04,667] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50649, SOMAXCONN=128.
  INFO root [0x00000cc0] [2018-05-27 11:30:04,667] - server-configs:
  INFO root [0x00000cc0] [2018-05-27 11:30:04,667] - 	gameUpdateHertz : 10
  INFO root [0x00000cc0] [2018-05-27 11:30:04,667] - 	entryScriptFile : kbemain
  INFO root [0x00000cc0] [2018-05-27 11:30:04,667] - 	internalAddr : 192.168.0.104:50649
  INFO root [0x00000cc0] [2018-05-27 11:30:04,668] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00000cc0] [2018-05-27 11:30:04,668] - 	componentID : 7001
  INFO root [0x00000cc0] [2018-05-27 11:30:06,375] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 5088. PID: 12268 ----
  INFO root [0x00000cc0] [2018-05-27 11:30:06,375] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000cc0] [2018-05-27 11:30:06,376] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000cc0] [2018-05-27 11:30:06,376] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,581] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,589] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,603] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,646] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,652] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,653] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,654] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,707] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000cc0] [2018-05-27 11:30:06,754] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000cc0] [2018-05-27 11:30:06,754] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,876] - loaded entity-script:Account(1).
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,877] - loaded entity-script:CheckName(2).
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,896] - loaded entity-script:Halls(3).
 DEBUG root [0x00000cc0] [2018-05-27 11:30:06,920] - loaded entity-script:Room(4).
  INFO root [0x00000cc0] [2018-05-27 11:30:06,921] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00000cc0] [2018-05-27 11:30:06,934] - TelnetServer server is running on port 40000
  INFO root [0x00000cc0] [2018-05-27 11:30:07,275] - ---- baseapp is running ----
 DEBUG root [0x00000cc0] [2018-05-27 11:30:07,275] - Components::process(): Request for the process of identity...
  WARN root [0x00000cc0] [2018-05-27 11:30:13,379] - EntityApp::checkTickPeriod: tick took 6104% (6.10 seconds)!
  INFO root [0x00000cc0] [2018-05-27 11:30:14,461] - Components::findComponents: find logger(1)...
  INFO root [0x00000cc0] [2018-05-27 11:30:14,476] - Components::findComponents: found logger, addr:192.168.0.104:50648
  INFO root [0x00000cc0] [2018-05-27 11:30:14,477] - Components::addComponent: reset orderLog, uid=5088!
  INFO root [0x00000cc0] [2018-05-27 11:30:14,477] - Components::addComponent[logger], uid=5088, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000cc0] [2018-05-27 11:30:14,479] - Components::findComponents: find dbmgr(2)...
  WARN root [0x00000cc0] [2018-05-27 11:30:15,580] - Forwarding logs to logger[192.168.0.104:50648/0/0/0]...
 ERROR root [0x00000cc0] [2018-05-27 11:30:22,474] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000cc0] [2018-05-27 11:30:22,478] - The following logs sent to logger failed:
  WARN root [0x00000cc0] [2018-05-27 11:30:22,478] - ==> [2018-05-27 11:30:22 472] TCPPacketReceiver::processPendingEvents(192.168.0.104:50648): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000cc0] [2018-05-27 11:30:22,478] - ==> [2018-05-27 11:30:22 475] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003234] [2018-05-27 11:30:26,077] - 
  INFO root [0x00003234] [2018-05-27 11:30:26,077] - -----------------------------------------------------------------------------------------


  INFO root [0x00003234] [2018-05-27 11:30:26,078] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003234] [2018-05-27 11:30:26,078] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003234] [2018-05-27 11:30:26,078] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003234] [2018-05-27 11:30:26,080] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00003234] [2018-05-27 11:30:26,080] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50672 )
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50672, SOMAXCONN=128.
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - server-configs:
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - 	gameUpdateHertz : 10
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - 	entryScriptFile : kbemain
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - 	internalAddr : 192.168.0.104:50672
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00003234] [2018-05-27 11:30:26,082] - 	componentID : 7001
  INFO root [0x00003234] [2018-05-27 11:30:27,797] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 5157. PID: 11512 ----
  INFO root [0x00003234] [2018-05-27 11:30:27,798] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003234] [2018-05-27 11:30:27,798] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003234] [2018-05-27 11:30:27,798] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003234] [2018-05-27 11:30:27,921] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003234] [2018-05-27 11:30:27,921] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003234] [2018-05-27 11:30:27,921] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003234] [2018-05-27 11:30:27,924] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003234] [2018-05-27 11:30:27,925] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003234] [2018-05-27 11:30:27,925] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003234] [2018-05-27 11:30:27,925] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003234] [2018-05-27 11:30:27,953] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003234] [2018-05-27 11:30:27,980] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003234] [2018-05-27 11:30:27,980] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003234] [2018-05-27 11:30:27,993] - loaded entity-script:Account(1).
 DEBUG root [0x00003234] [2018-05-27 11:30:27,993] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003234] [2018-05-27 11:30:27,994] - loaded entity-script:Halls(3).
 DEBUG root [0x00003234] [2018-05-27 11:30:27,995] - loaded entity-script:Room(4).
  INFO root [0x00003234] [2018-05-27 11:30:27,996] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003234] [2018-05-27 11:30:27,996] - TelnetServer server is running on port 40000
  INFO root [0x00003234] [2018-05-27 11:30:28,275] - ---- baseapp is running ----
 DEBUG root [0x00003234] [2018-05-27 11:30:28,275] - Components::process(): Request for the process of identity...
  WARN root [0x00003234] [2018-05-27 11:30:34,363] - EntityApp::checkTickPeriod: tick took 6088% (6.09 seconds)!
  INFO root [0x00003234] [2018-05-27 11:30:35,475] - Components::findComponents: find logger(1)...
  INFO root [0x00003234] [2018-05-27 11:30:35,573] - Components::findComponents: found logger, addr:192.168.0.104:50671
  INFO root [0x00003234] [2018-05-27 11:30:35,573] - Components::addComponent: reset orderLog, uid=5157!
  INFO root [0x00003234] [2018-05-27 11:30:35,574] - Components::addComponent[logger], uid=5157, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003234] [2018-05-27 11:30:35,574] - Components::findComponents: find dbmgr(2)...
  WARN root [0x00003234] [2018-05-27 11:30:36,675] - EntityApp::checkTickPeriod: tick took 1300% (1.30 seconds)!
  WARN root [0x00003234] [2018-05-27 11:30:36,677] - Forwarding logs to logger[192.168.0.104:50671/0/0/0]...
 ERROR root [0x00003234] [2018-05-27 11:30:39,020] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003234] [2018-05-27 11:30:39,030] - The following logs sent to logger failed:
  WARN root [0x00003234] [2018-05-27 11:30:39,030] - ==> [2018-05-27 11:30:39 019] TCPPacketReceiver::processPendingEvents(192.168.0.104:50671): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003234] [2018-05-27 11:30:39,030] - ==> [2018-05-27 11:30:39 020] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003228] [2018-05-27 11:31:11,847] - 
  INFO root [0x00003228] [2018-05-27 11:31:11,847] - -----------------------------------------------------------------------------------------


  INFO root [0x00003228] [2018-05-27 11:31:11,848] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003228] [2018-05-27 11:31:11,848] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003228] [2018-05-27 11:31:11,848] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003228] [2018-05-27 11:31:11,851] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00003228] [2018-05-27 11:31:11,852] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50692 )
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50692, SOMAXCONN=128.
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - server-configs:
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - 	gameUpdateHertz : 10
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - 	entryScriptFile : kbemain
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - 	internalAddr : 192.168.0.104:50692
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00003228] [2018-05-27 11:31:11,854] - 	componentID : 7001
  WARN root [0x00003228] [2018-05-27 11:31:12,380] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20575, errorno=10048
  INFO root [0x00003228] [2018-05-27 11:31:12,384] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 5307. PID: 3060 ----
  INFO root [0x00003228] [2018-05-27 11:31:12,384] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003228] [2018-05-27 11:31:12,385] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003228] [2018-05-27 11:31:12,385] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003228] [2018-05-27 11:31:12,509] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003228] [2018-05-27 11:31:12,509] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003228] [2018-05-27 11:31:12,510] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003228] [2018-05-27 11:31:12,512] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003228] [2018-05-27 11:31:12,513] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003228] [2018-05-27 11:31:12,513] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003228] [2018-05-27 11:31:12,513] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003228] [2018-05-27 11:31:12,541] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003228] [2018-05-27 11:31:12,569] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003228] [2018-05-27 11:31:12,570] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003228] [2018-05-27 11:31:12,583] - loaded entity-script:Account(1).
 DEBUG root [0x00003228] [2018-05-27 11:31:12,584] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003228] [2018-05-27 11:31:12,585] - loaded entity-script:Halls(3).
 DEBUG root [0x00003228] [2018-05-27 11:31:12,586] - loaded entity-script:Room(4).
  INFO root [0x00003228] [2018-05-27 11:31:12,586] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003228] [2018-05-27 11:31:12,586] - TelnetServer server is running on port 40000
  INFO root [0x00003228] [2018-05-27 11:31:12,867] - ---- baseapp is running ----
 DEBUG root [0x00003228] [2018-05-27 11:31:12,867] - Components::process(): Request for the process of identity...
  WARN root [0x00003228] [2018-05-27 11:31:18,946] - EntityApp::checkTickPeriod: tick took 6078% (6.08 seconds)!
  INFO root [0x00003228] [2018-05-27 11:31:20,050] - Components::findComponents: find logger(1)...
  INFO root [0x00003228] [2018-05-27 11:31:20,134] - Components::findComponents: found logger, addr:192.168.0.104:50691
  INFO root [0x00003228] [2018-05-27 11:31:20,135] - Components::addComponent: reset orderLog, uid=5307!
  INFO root [0x00003228] [2018-05-27 11:31:20,136] - Components::addComponent[logger], uid=5307, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003228] [2018-05-27 11:31:20,138] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003228] [2018-05-27 11:31:20,238] - Components::findComponents: found dbmgr, addr:192.168.0.104:50688
  INFO root [0x00003228] [2018-05-27 11:31:20,239] - Components::addComponent: reset orderLog, uid=5307!
  INFO root [0x00003228] [2018-05-27 11:31:20,239] - Components::addComponent[dbmgr], uid=5307, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003228] [2018-05-27 11:31:20,239] - Components::findComponents: found dbmgr, addr:192.168.0.104:50688
  WARN root [0x00003228] [2018-05-27 11:31:21,239] - Forwarding logs to logger[192.168.0.104:50691/0/0/0]...
 ERROR root [0x00003228] [2018-05-27 11:32:36,365] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003228] [2018-05-27 11:32:36,371] - The following logs sent to logger failed:
  WARN root [0x00003228] [2018-05-27 11:32:36,371] - ==> [2018-05-27 11:32:36 360] TCPPacketReceiver::processPendingEvents(192.168.0.104:50691): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003228] [2018-05-27 11:32:36,371] - ==> [2018-05-27 11:32:36 365] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003228] [2018-05-27 11:32:36,421] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50688): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003228] [2018-05-27 11:32:36,423] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003228] [2018-05-27 11:32:36,432] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003228] [2018-05-27 11:32:36,432] - onBaseAppShutDown: state=0
  INFO root [0x00003228] [2018-05-27 11:32:36,432] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003228] [2018-05-27 11:32:36,432] - onBaseAppShutDown: state=1
  INFO root [0x00003228] [2018-05-27 11:32:36,433] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003228] [2018-05-27 11:32:36,433] - onBaseAppShutDown: state=2
 DEBUG root [0x00003228] [2018-05-27 11:32:36,534] - Halls::~Halls(): 1
 DEBUG root [0x00003228] [2018-05-27 11:32:36,557] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003228] [2018-05-27 11:32:36,557] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003228] [2018-05-27 11:32:36,557] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003228] [2018-05-27 11:32:36,557] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003228] [2018-05-27 11:32:36,557] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003228] [2018-05-27 11:32:36,557] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003228] [2018-05-27 11:32:36,558] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003228] [2018-05-27 11:32:36,558] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003228] [2018-05-27 11:32:36,566] - Script::uninstall(): is successfully!
 DEBUG root [0x00003228] [2018-05-27 11:32:36,566] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003298] [2018-05-27 11:32:37,689] - 
  INFO root [0x00003298] [2018-05-27 11:32:37,690] - -----------------------------------------------------------------------------------------


  INFO root [0x00003298] [2018-05-27 11:32:37,691] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003298] [2018-05-27 11:32:37,691] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003298] [2018-05-27 11:32:37,691] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003298] [2018-05-27 11:32:37,694] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00003298] [2018-05-27 11:32:37,694] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00003298] [2018-05-27 11:32:37,695] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50748 )
  INFO root [0x00003298] [2018-05-27 11:32:37,696] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50748, SOMAXCONN=128.
  INFO root [0x00003298] [2018-05-27 11:32:37,696] - server-configs:
  INFO root [0x00003298] [2018-05-27 11:32:37,696] - 	gameUpdateHertz : 10
  INFO root [0x00003298] [2018-05-27 11:32:37,696] - 	entryScriptFile : kbemain
  INFO root [0x00003298] [2018-05-27 11:32:37,696] - 	internalAddr : 192.168.0.104:50748
  INFO root [0x00003298] [2018-05-27 11:32:37,696] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00003298] [2018-05-27 11:32:37,696] - 	componentID : 7001
  INFO root [0x00003298] [2018-05-27 11:32:39,419] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 5588. PID: 13252 ----
  INFO root [0x00003298] [2018-05-27 11:32:39,419] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003298] [2018-05-27 11:32:39,420] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003298] [2018-05-27 11:32:39,420] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003298] [2018-05-27 11:32:39,544] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003298] [2018-05-27 11:32:39,544] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003298] [2018-05-27 11:32:39,545] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003298] [2018-05-27 11:32:39,548] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003298] [2018-05-27 11:32:39,548] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003298] [2018-05-27 11:32:39,548] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003298] [2018-05-27 11:32:39,549] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003298] [2018-05-27 11:32:39,577] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003298] [2018-05-27 11:32:39,605] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003298] [2018-05-27 11:32:39,605] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003298] [2018-05-27 11:32:39,618] - loaded entity-script:Account(1).
 DEBUG root [0x00003298] [2018-05-27 11:32:39,619] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003298] [2018-05-27 11:32:39,625] - loaded entity-script:Halls(3).
 DEBUG root [0x00003298] [2018-05-27 11:32:39,626] - loaded entity-script:Room(4).
  INFO root [0x00003298] [2018-05-27 11:32:39,627] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003298] [2018-05-27 11:32:39,627] - TelnetServer server is running on port 40000
  INFO root [0x00003298] [2018-05-27 11:32:39,903] - ---- baseapp is running ----
 DEBUG root [0x00003298] [2018-05-27 11:32:39,903] - Components::process(): Request for the process of identity...
  WARN root [0x00003298] [2018-05-27 11:32:45,987] - EntityApp::checkTickPeriod: tick took 6083% (6.08 seconds)!
 DEBUG root [0x00003298] [2018-05-27 11:32:46,905] - Baseapp::lookApp: 192.168.0.104:50774/0/0/0
  INFO root [0x00003298] [2018-05-27 11:32:47,093] - Components::findComponents: find logger(1)...
  INFO root [0x00003298] [2018-05-27 11:32:47,102] - Components::findComponents: found logger, addr:192.168.0.104:50743
  INFO root [0x00003298] [2018-05-27 11:32:47,103] - Components::addComponent: reset orderLog, uid=5588!
  INFO root [0x00003298] [2018-05-27 11:32:47,103] - Components::addComponent[logger], uid=5588, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003298] [2018-05-27 11:32:47,104] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003298] [2018-05-27 11:32:47,207] - Components::findComponents: found dbmgr, addr:192.168.0.104:50741
  INFO root [0x00003298] [2018-05-27 11:32:47,208] - Components::addComponent: reset orderLog, uid=5588!
  INFO root [0x00003298] [2018-05-27 11:32:47,209] - Components::addComponent[dbmgr], uid=5588, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003298] [2018-05-27 11:32:47,210] - Components::findComponents: found dbmgr, addr:192.168.0.104:50741
  WARN root [0x00003298] [2018-05-27 11:32:48,210] - Forwarding logs to logger[192.168.0.104:50743/0/0/0]...
 ERROR root [0x00003298] [2018-05-27 11:34:43,104] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003298] [2018-05-27 11:34:43,113] - The following logs sent to logger failed:
  WARN root [0x00003298] [2018-05-27 11:34:43,113] - ==> [2018-05-27 11:34:43 103] TCPPacketReceiver::processPendingEvents(192.168.0.104:50743): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003298] [2018-05-27 11:34:43,113] - ==> [2018-05-27 11:34:43 105] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003298] [2018-05-27 11:34:43,166] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50741): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003298] [2018-05-27 11:34:43,167] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003298] [2018-05-27 11:34:43,174] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003298] [2018-05-27 11:34:43,176] - onBaseAppShutDown: state=0
  INFO root [0x00003298] [2018-05-27 11:34:43,176] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003298] [2018-05-27 11:34:43,176] - onBaseAppShutDown: state=1
  INFO root [0x00003298] [2018-05-27 11:34:43,176] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003298] [2018-05-27 11:34:43,176] - onBaseAppShutDown: state=2
 ERROR root [0x00003298] [2018-05-27 11:34:43,201] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00003298] [2018-05-27 11:34:43,201] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003298] [2018-05-27 11:34:43,202] - Account::~Account(): 2002
 DEBUG root [0x00003298] [2018-05-27 11:34:43,202] - Halls::~Halls(): 2001
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003298] [2018-05-27 11:34:43,203] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003298] [2018-05-27 11:34:43,212] - Script::uninstall(): is successfully!
 DEBUG root [0x00003298] [2018-05-27 11:34:43,213] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002b08] [2018-05-27 11:34:44,342] - 
  INFO root [0x00002b08] [2018-05-27 11:34:44,347] - -----------------------------------------------------------------------------------------


  INFO root [0x00002b08] [2018-05-27 11:34:44,348] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002b08] [2018-05-27 11:34:44,348] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002b08] [2018-05-27 11:34:44,348] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002b08] [2018-05-27 11:34:44,351] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00002b08] [2018-05-27 11:34:44,352] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50814 )
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50814, SOMAXCONN=128.
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - server-configs:
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - 	gameUpdateHertz : 10
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - 	entryScriptFile : kbemain
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - 	internalAddr : 192.168.0.104:50814
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00002b08] [2018-05-27 11:34:44,353] - 	componentID : 7001
  INFO root [0x00002b08] [2018-05-27 11:34:46,074] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 5999. PID: 12544 ----
  INFO root [0x00002b08] [2018-05-27 11:34:46,075] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002b08] [2018-05-27 11:34:46,076] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002b08] [2018-05-27 11:34:46,076] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,199] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,199] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,200] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,203] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,203] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,203] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,203] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,232] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002b08] [2018-05-27 11:34:46,261] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002b08] [2018-05-27 11:34:46,261] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,277] - loaded entity-script:Account(1).
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,278] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,339] - loaded entity-script:Halls(3).
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,340] - loaded entity-script:Room(4).
  INFO root [0x00002b08] [2018-05-27 11:34:46,340] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002b08] [2018-05-27 11:34:46,340] - TelnetServer server is running on port 40000
  INFO root [0x00002b08] [2018-05-27 11:34:46,638] - ---- baseapp is running ----
 DEBUG root [0x00002b08] [2018-05-27 11:34:46,638] - Components::process(): Request for the process of identity...
  WARN root [0x00002b08] [2018-05-27 11:34:52,725] - EntityApp::checkTickPeriod: tick took 6087% (6.09 seconds)!
 DEBUG root [0x00002b08] [2018-05-27 11:34:53,638] - Baseapp::lookApp: 192.168.0.104:50841/0/0/0
  INFO root [0x00002b08] [2018-05-27 11:34:53,750] - Components::findComponents: find logger(1)...
  INFO root [0x00002b08] [2018-05-27 11:34:53,785] - Components::findComponents: found logger, addr:192.168.0.104:50810
  INFO root [0x00002b08] [2018-05-27 11:34:53,786] - Components::addComponent: reset orderLog, uid=5999!
  INFO root [0x00002b08] [2018-05-27 11:34:53,786] - Components::addComponent[logger], uid=5999, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002b08] [2018-05-27 11:34:53,787] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002b08] [2018-05-27 11:34:53,888] - Components::findComponents: found dbmgr, addr:192.168.0.104:50813
  INFO root [0x00002b08] [2018-05-27 11:34:53,888] - Components::addComponent: reset orderLog, uid=5999!
  INFO root [0x00002b08] [2018-05-27 11:34:53,889] - Components::addComponent[dbmgr], uid=5999, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002b08] [2018-05-27 11:34:53,889] - Components::findComponents: found dbmgr, addr:192.168.0.104:50813
  WARN root [0x00002b08] [2018-05-27 11:34:54,889] - Forwarding logs to logger[192.168.0.104:50810/0/0/0]...
 ERROR root [0x00002b08] [2018-05-27 11:54:57,575] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002b08] [2018-05-27 11:54:57,587] - The following logs sent to logger failed:
  WARN root [0x00002b08] [2018-05-27 11:54:57,587] - ==> [2018-05-27 11:54:57 574] TCPPacketReceiver::processPendingEvents(192.168.0.104:50810): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002b08] [2018-05-27 11:54:57,587] - ==> [2018-05-27 11:54:57 576] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002b08] [2018-05-27 11:54:57,640] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50813): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002b08] [2018-05-27 11:54:57,646] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002b08] [2018-05-27 11:54:57,651] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002b08] [2018-05-27 11:54:57,652] - onBaseAppShutDown: state=0
  INFO root [0x00002b08] [2018-05-27 11:54:57,652] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002b08] [2018-05-27 11:54:57,653] - onBaseAppShutDown: state=1
  INFO root [0x00002b08] [2018-05-27 11:54:57,653] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002b08] [2018-05-27 11:54:57,653] - onBaseAppShutDown: state=2
 ERROR root [0x00002b08] [2018-05-27 11:54:57,661] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00002b08] [2018-05-27 11:54:57,662] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,662] - Account::~Account(): 2002
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,663] - Room::~Room(): 2003
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,663] - Halls::~Halls(): 2001
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,663] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,664] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,664] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,664] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,664] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,664] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,664] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,664] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002b08] [2018-05-27 11:54:57,675] - Script::uninstall(): is successfully!
 DEBUG root [0x00002b08] [2018-05-27 11:54:57,675] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00000fa8] [2018-05-27 11:55:00,455] - 
  INFO root [0x00000fa8] [2018-05-27 11:55:00,455] - -----------------------------------------------------------------------------------------


  INFO root [0x00000fa8] [2018-05-27 11:55:00,456] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00000fa8] [2018-05-27 11:55:00,456] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00000fa8] [2018-05-27 11:55:00,456] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00000fa8] [2018-05-27 11:55:00,460] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00000fa8] [2018-05-27 11:55:00,460] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00000fa8] [2018-05-27 11:55:00,461] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:50962 )
  INFO root [0x00000fa8] [2018-05-27 11:55:00,461] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:50962, SOMAXCONN=128.
  INFO root [0x00000fa8] [2018-05-27 11:55:00,461] - server-configs:
  INFO root [0x00000fa8] [2018-05-27 11:55:00,462] - 	gameUpdateHertz : 10
  INFO root [0x00000fa8] [2018-05-27 11:55:00,462] - 	entryScriptFile : kbemain
  INFO root [0x00000fa8] [2018-05-27 11:55:00,462] - 	internalAddr : 192.168.0.104:50962
  INFO root [0x00000fa8] [2018-05-27 11:55:00,462] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00000fa8] [2018-05-27 11:55:00,462] - 	componentID : 7001
  INFO root [0x00000fa8] [2018-05-27 11:55:02,199] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 9974. PID: 13100 ----
  INFO root [0x00000fa8] [2018-05-27 11:55:02,200] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00000fa8] [2018-05-27 11:55:02,200] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000fa8] [2018-05-27 11:55:02,200] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,326] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,327] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,327] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,330] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,330] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,330] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,331] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,365] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000fa8] [2018-05-27 11:55:02,399] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00000fa8] [2018-05-27 11:55:02,399] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,419] - loaded entity-script:Account(1).
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,420] - loaded entity-script:CheckName(2).
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,425] - loaded entity-script:Halls(3).
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,428] - loaded entity-script:Room(4).
  INFO root [0x00000fa8] [2018-05-27 11:55:02,428] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00000fa8] [2018-05-27 11:55:02,429] - TelnetServer server is running on port 40000
  INFO root [0x00000fa8] [2018-05-27 11:55:02,734] - ---- baseapp is running ----
 DEBUG root [0x00000fa8] [2018-05-27 11:55:02,734] - Components::process(): Request for the process of identity...
  WARN root [0x00000fa8] [2018-05-27 11:55:08,814] - EntityApp::checkTickPeriod: tick took 6079% (6.08 seconds)!
  INFO root [0x00000fa8] [2018-05-27 11:55:09,835] - Components::findComponents: find logger(1)...
  INFO root [0x00000fa8] [2018-05-27 11:55:09,889] - Components::findComponents: found logger, addr:192.168.0.104:50960
  INFO root [0x00000fa8] [2018-05-27 11:55:09,889] - Components::addComponent: reset orderLog, uid=9974!
  INFO root [0x00000fa8] [2018-05-27 11:55:09,889] - Components::addComponent[logger], uid=9974, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000fa8] [2018-05-27 11:55:09,890] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00000fa8] [2018-05-27 11:55:09,997] - Components::findComponents: found dbmgr, addr:192.168.0.104:50966
  INFO root [0x00000fa8] [2018-05-27 11:55:09,998] - Components::addComponent: reset orderLog, uid=9974!
  INFO root [0x00000fa8] [2018-05-27 11:55:09,998] - Components::addComponent[dbmgr], uid=9974, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000fa8] [2018-05-27 11:55:09,999] - Components::findComponents: found dbmgr, addr:192.168.0.104:50966
  WARN root [0x00000fa8] [2018-05-27 11:55:10,999] - EntityApp::checkTickPeriod: tick took 1263% (1.26 seconds)!
  WARN root [0x00000fa8] [2018-05-27 11:55:11,002] - Forwarding logs to logger[192.168.0.104:50960/0/0/0]...
 ERROR root [0x00000fa8] [2018-05-27 11:57:18,895] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000fa8] [2018-05-27 11:57:18,904] - The following logs sent to logger failed:
  WARN root [0x00000fa8] [2018-05-27 11:57:18,904] - ==> [2018-05-27 11:57:18 889] TCPPacketReceiver::processPendingEvents(192.168.0.104:50960): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000fa8] [2018-05-27 11:57:18,904] - ==> [2018-05-27 11:57:18 896] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000fa8] [2018-05-27 11:57:18,955] - TCPPacketReceiver::processPendingEvents(192.168.0.104:50966): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000fa8] [2018-05-27 11:57:18,961] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00000fa8] [2018-05-27 11:57:18,967] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00000fa8] [2018-05-27 11:57:18,969] - onBaseAppShutDown: state=0
  INFO root [0x00000fa8] [2018-05-27 11:57:18,969] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00000fa8] [2018-05-27 11:57:18,971] - onBaseAppShutDown: state=1
  INFO root [0x00000fa8] [2018-05-27 11:57:18,971] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00000fa8] [2018-05-27 11:57:18,971] - onBaseAppShutDown: state=2
 ERROR root [0x00000fa8] [2018-05-27 11:57:18,979] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00000fa8] [2018-05-27 11:57:18,980] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,981] - Account::~Account(): 2002
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,981] - Room::~Room(): 2003
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,981] - Halls::~Halls(): 2001
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,982] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000fa8] [2018-05-27 11:57:18,993] - Script::uninstall(): is successfully!
 DEBUG root [0x00000fa8] [2018-05-27 11:57:18,993] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000037f8] [2018-05-27 11:57:20,168] - 
  INFO root [0x000037f8] [2018-05-27 11:57:20,169] - -----------------------------------------------------------------------------------------


  INFO root [0x000037f8] [2018-05-27 11:57:20,169] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000037f8] [2018-05-27 11:57:20,170] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000037f8] [2018-05-27 11:57:20,170] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000037f8] [2018-05-27 11:57:20,175] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x000037f8] [2018-05-27 11:57:20,175] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x000037f8] [2018-05-27 11:57:20,176] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51065 )
  INFO root [0x000037f8] [2018-05-27 11:57:20,176] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51065, SOMAXCONN=128.
  INFO root [0x000037f8] [2018-05-27 11:57:20,177] - server-configs:
  INFO root [0x000037f8] [2018-05-27 11:57:20,177] - 	gameUpdateHertz : 10
  INFO root [0x000037f8] [2018-05-27 11:57:20,177] - 	entryScriptFile : kbemain
  INFO root [0x000037f8] [2018-05-27 11:57:20,177] - 	internalAddr : 192.168.0.104:51065
  INFO root [0x000037f8] [2018-05-27 11:57:20,177] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x000037f8] [2018-05-27 11:57:20,177] - 	componentID : 7001
  INFO root [0x000037f8] [2018-05-27 11:57:21,872] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 10428. PID: 9308 ----
  INFO root [0x000037f8] [2018-05-27 11:57:21,873] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000037f8] [2018-05-27 11:57:21,873] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000037f8] [2018-05-27 11:57:21,874] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000037f8] [2018-05-27 11:57:21,998] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000037f8] [2018-05-27 11:57:21,999] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000037f8] [2018-05-27 11:57:21,999] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,002] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,002] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,003] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,003] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,031] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000037f8] [2018-05-27 11:57:22,061] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000037f8] [2018-05-27 11:57:22,061] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,075] - loaded entity-script:Account(1).
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,076] - loaded entity-script:CheckName(2).
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,082] - loaded entity-script:Halls(3).
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,082] - loaded entity-script:Room(4).
  INFO root [0x000037f8] [2018-05-27 11:57:22,083] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000037f8] [2018-05-27 11:57:22,083] - TelnetServer server is running on port 40000
  INFO root [0x000037f8] [2018-05-27 11:57:22,380] - ---- baseapp is running ----
 DEBUG root [0x000037f8] [2018-05-27 11:57:22,380] - Components::process(): Request for the process of identity...
  WARN root [0x000037f8] [2018-05-27 11:57:28,495] - EntityApp::checkTickPeriod: tick took 6114% (6.11 seconds)!
  INFO root [0x000037f8] [2018-05-27 11:57:29,571] - Components::findComponents: find logger(1)...
  INFO root [0x000037f8] [2018-05-27 11:57:29,593] - Components::findComponents: found logger, addr:192.168.0.104:51061
  INFO root [0x000037f8] [2018-05-27 11:57:29,594] - Components::addComponent: reset orderLog, uid=10428!
  INFO root [0x000037f8] [2018-05-27 11:57:29,595] - Components::addComponent[logger], uid=10428, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000037f8] [2018-05-27 11:57:29,597] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000037f8] [2018-05-27 11:57:29,696] - Components::findComponents: found dbmgr, addr:192.168.0.104:51063
  INFO root [0x000037f8] [2018-05-27 11:57:29,697] - Components::addComponent: reset orderLog, uid=10428!
  INFO root [0x000037f8] [2018-05-27 11:57:29,697] - Components::addComponent[dbmgr], uid=10428, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000037f8] [2018-05-27 11:57:29,697] - Components::findComponents: found dbmgr, addr:192.168.0.104:51063
  WARN root [0x000037f8] [2018-05-27 11:57:30,697] - Forwarding logs to logger[192.168.0.104:51061/0/0/0]...
 ERROR root [0x000037f8] [2018-05-27 12:00:37,653] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000037f8] [2018-05-27 12:00:37,665] - The following logs sent to logger failed:
  WARN root [0x000037f8] [2018-05-27 12:00:37,665] - ==> [2018-05-27 12:00:37 651] TCPPacketReceiver::processPendingEvents(192.168.0.104:51061): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000037f8] [2018-05-27 12:00:37,665] - ==> [2018-05-27 12:00:37 654] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000037f8] [2018-05-27 12:00:37,717] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51063): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000037f8] [2018-05-27 12:00:37,724] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000037f8] [2018-05-27 12:00:37,728] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000037f8] [2018-05-27 12:00:37,730] - onBaseAppShutDown: state=0
  INFO root [0x000037f8] [2018-05-27 12:00:37,730] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000037f8] [2018-05-27 12:00:37,730] - onBaseAppShutDown: state=1
  INFO root [0x000037f8] [2018-05-27 12:00:37,730] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000037f8] [2018-05-27 12:00:37,730] - onBaseAppShutDown: state=2
 ERROR root [0x000037f8] [2018-05-27 12:00:37,738] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000037f8] [2018-05-27 12:00:37,739] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,740] - Account::~Account(): 2002
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,740] - Room::~Room(): 2003
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,740] - Halls::~Halls(): 2001
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,741] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000037f8] [2018-05-27 12:00:37,753] - Script::uninstall(): is successfully!
 DEBUG root [0x000037f8] [2018-05-27 12:00:37,753] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000015c8] [2018-05-27 12:00:38,955] - 
  INFO root [0x000015c8] [2018-05-27 12:00:38,955] - -----------------------------------------------------------------------------------------


  INFO root [0x000015c8] [2018-05-27 12:00:38,956] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000015c8] [2018-05-27 12:00:38,957] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000015c8] [2018-05-27 12:00:38,957] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000015c8] [2018-05-27 12:00:38,959] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x000015c8] [2018-05-27 12:00:38,959] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x000015c8] [2018-05-27 12:00:38,960] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51154 )
  INFO root [0x000015c8] [2018-05-27 12:00:38,960] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51154, SOMAXCONN=128.
  INFO root [0x000015c8] [2018-05-27 12:00:38,960] - server-configs:
  INFO root [0x000015c8] [2018-05-27 12:00:38,960] - 	gameUpdateHertz : 10
  INFO root [0x000015c8] [2018-05-27 12:00:38,960] - 	entryScriptFile : kbemain
  INFO root [0x000015c8] [2018-05-27 12:00:38,960] - 	internalAddr : 192.168.0.104:51154
  INFO root [0x000015c8] [2018-05-27 12:00:38,961] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x000015c8] [2018-05-27 12:00:38,961] - 	componentID : 7001
  INFO root [0x000015c8] [2018-05-27 12:00:40,679] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 11077. PID: 1956 ----
  INFO root [0x000015c8] [2018-05-27 12:00:40,680] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000015c8] [2018-05-27 12:00:40,680] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000015c8] [2018-05-27 12:00:40,680] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,804] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,804] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,805] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,807] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,808] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,808] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,808] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,838] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000015c8] [2018-05-27 12:00:40,869] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000015c8] [2018-05-27 12:00:40,870] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,884] - loaded entity-script:Account(1).
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,885] - loaded entity-script:CheckName(2).
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,891] - loaded entity-script:Halls(3).
 DEBUG root [0x000015c8] [2018-05-27 12:00:40,892] - loaded entity-script:Room(4).
  INFO root [0x000015c8] [2018-05-27 12:00:40,892] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000015c8] [2018-05-27 12:00:40,893] - TelnetServer server is running on port 40000
  INFO root [0x000015c8] [2018-05-27 12:00:41,192] - ---- baseapp is running ----
 DEBUG root [0x000015c8] [2018-05-27 12:00:41,192] - Components::process(): Request for the process of identity...
  WARN root [0x000015c8] [2018-05-27 12:00:47,269] - EntityApp::checkTickPeriod: tick took 6077% (6.08 seconds)!
  INFO root [0x000015c8] [2018-05-27 12:00:48,292] - Components::findComponents: find logger(1)...
  INFO root [0x000015c8] [2018-05-27 12:00:48,377] - Components::findComponents: found logger, addr:192.168.0.104:51147
  INFO root [0x000015c8] [2018-05-27 12:00:48,378] - Components::addComponent: reset orderLog, uid=11077!
  INFO root [0x000015c8] [2018-05-27 12:00:48,378] - Components::addComponent[logger], uid=11077, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000015c8] [2018-05-27 12:00:48,380] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000015c8] [2018-05-27 12:00:48,481] - Components::findComponents: found dbmgr, addr:192.168.0.104:51152
  INFO root [0x000015c8] [2018-05-27 12:00:48,482] - Components::addComponent: reset orderLog, uid=11077!
  INFO root [0x000015c8] [2018-05-27 12:00:48,482] - Components::addComponent[dbmgr], uid=11077, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000015c8] [2018-05-27 12:00:48,483] - Components::findComponents: found dbmgr, addr:192.168.0.104:51152
  WARN root [0x000015c8] [2018-05-27 12:00:49,483] - EntityApp::checkTickPeriod: tick took 1291% (1.29 seconds)!
  WARN root [0x000015c8] [2018-05-27 12:00:49,483] - Forwarding logs to logger[192.168.0.104:51147/0/0/0]...
 ERROR root [0x000015c8] [2018-05-27 12:02:02,709] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000015c8] [2018-05-27 12:02:02,721] - The following logs sent to logger failed:
  WARN root [0x000015c8] [2018-05-27 12:02:02,721] - ==> [2018-05-27 12:02:02 707] TCPPacketReceiver::processPendingEvents(192.168.0.104:51147): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000015c8] [2018-05-27 12:02:02,721] - ==> [2018-05-27 12:02:02 710] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000015c8] [2018-05-27 12:02:02,772] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51152): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000015c8] [2018-05-27 12:02:02,774] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000015c8] [2018-05-27 12:02:02,784] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000015c8] [2018-05-27 12:02:02,787] - onBaseAppShutDown: state=0
  INFO root [0x000015c8] [2018-05-27 12:02:02,787] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000015c8] [2018-05-27 12:02:02,787] - onBaseAppShutDown: state=1
  INFO root [0x000015c8] [2018-05-27 12:02:02,787] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000015c8] [2018-05-27 12:02:02,787] - onBaseAppShutDown: state=2
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,795] - Halls::~Halls(): 2001
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,796] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,796] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,796] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,796] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,797] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,797] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,797] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,797] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000015c8] [2018-05-27 12:02:02,807] - Script::uninstall(): is successfully!
 DEBUG root [0x000015c8] [2018-05-27 12:02:02,807] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002368] [2018-05-27 12:02:07,001] - 
  INFO root [0x00002368] [2018-05-27 12:02:07,002] - -----------------------------------------------------------------------------------------


  INFO root [0x00002368] [2018-05-27 12:02:07,002] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002368] [2018-05-27 12:02:07,002] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002368] [2018-05-27 12:02:07,002] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002368] [2018-05-27 12:02:07,005] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00002368] [2018-05-27 12:02:07,005] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00002368] [2018-05-27 12:02:07,006] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51220 )
  INFO root [0x00002368] [2018-05-27 12:02:07,006] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51220, SOMAXCONN=128.
  INFO root [0x00002368] [2018-05-27 12:02:07,006] - server-configs:
  INFO root [0x00002368] [2018-05-27 12:02:07,006] - 	gameUpdateHertz : 10
  INFO root [0x00002368] [2018-05-27 12:02:07,006] - 	entryScriptFile : kbemain
  INFO root [0x00002368] [2018-05-27 12:02:07,006] - 	internalAddr : 192.168.0.104:51220
  INFO root [0x00002368] [2018-05-27 12:02:07,006] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00002368] [2018-05-27 12:02:07,007] - 	componentID : 7001
  INFO root [0x00002368] [2018-05-27 12:02:08,737] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 11365. PID: 5828 ----
  INFO root [0x00002368] [2018-05-27 12:02:08,737] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002368] [2018-05-27 12:02:08,738] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002368] [2018-05-27 12:02:08,738] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002368] [2018-05-27 12:02:08,861] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002368] [2018-05-27 12:02:08,861] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002368] [2018-05-27 12:02:08,862] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002368] [2018-05-27 12:02:08,866] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002368] [2018-05-27 12:02:08,867] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002368] [2018-05-27 12:02:08,867] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002368] [2018-05-27 12:02:08,867] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002368] [2018-05-27 12:02:08,898] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002368] [2018-05-27 12:02:08,928] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002368] [2018-05-27 12:02:08,928] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002368] [2018-05-27 12:02:08,941] - loaded entity-script:Account(1).
 DEBUG root [0x00002368] [2018-05-27 12:02:08,942] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002368] [2018-05-27 12:02:08,947] - loaded entity-script:Halls(3).
 DEBUG root [0x00002368] [2018-05-27 12:02:08,948] - loaded entity-script:Room(4).
  INFO root [0x00002368] [2018-05-27 12:02:08,948] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002368] [2018-05-27 12:02:08,949] - TelnetServer server is running on port 40000
  INFO root [0x00002368] [2018-05-27 12:02:09,248] - ---- baseapp is running ----
 DEBUG root [0x00002368] [2018-05-27 12:02:09,248] - Components::process(): Request for the process of identity...
  WARN root [0x00002368] [2018-05-27 12:02:15,319] - EntityApp::checkTickPeriod: tick took 6072% (6.07 seconds)!
  INFO root [0x00002368] [2018-05-27 12:02:16,348] - Components::findComponents: find logger(1)...
  WARN root [0x00002368] [2018-05-27 12:02:16,659] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20665, errorno=10048
  WARN root [0x00002368] [2018-05-27 12:02:16,660] - EntityApp::checkTickPeriod: tick took 411% (0.41 seconds)!
  INFO root [0x00002368] [2018-05-27 12:02:17,703] - Components::findComponents: find logger(2)...
  INFO root [0x00002368] [2018-05-27 12:02:17,762] - Components::findComponents: found logger, addr:192.168.0.104:51227
  INFO root [0x00002368] [2018-05-27 12:02:17,763] - Components::addComponent: reset orderLog, uid=11365!
  INFO root [0x00002368] [2018-05-27 12:02:17,763] - Components::addComponent[logger], uid=11365, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002368] [2018-05-27 12:02:17,766] - Components::findComponents: find dbmgr(3)...
  INFO root [0x00002368] [2018-05-27 12:02:17,868] - Components::findComponents: found dbmgr, addr:192.168.0.104:51223
  INFO root [0x00002368] [2018-05-27 12:02:17,868] - Components::addComponent: reset orderLog, uid=11365!
  INFO root [0x00002368] [2018-05-27 12:02:17,869] - Components::addComponent[dbmgr], uid=11365, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002368] [2018-05-27 12:02:17,869] - Components::findComponents: found dbmgr, addr:192.168.0.104:51223
  WARN root [0x00002368] [2018-05-27 12:02:18,870] - Forwarding logs to logger[192.168.0.104:51227/0/0/0]...
 ERROR root [0x00002368] [2018-05-27 12:02:56,102] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002368] [2018-05-27 12:02:56,111] - The following logs sent to logger failed:
  WARN root [0x00002368] [2018-05-27 12:02:56,111] - ==> [2018-05-27 12:02:56 096] TCPPacketReceiver::processPendingEvents(192.168.0.104:51227): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002368] [2018-05-27 12:02:56,111] - ==> [2018-05-27 12:02:56 103] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002368] [2018-05-27 12:02:56,162] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51223): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002368] [2018-05-27 12:02:56,164] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002368] [2018-05-27 12:02:56,173] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002368] [2018-05-27 12:02:56,174] - onBaseAppShutDown: state=0
  INFO root [0x00002368] [2018-05-27 12:02:56,174] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002368] [2018-05-27 12:02:56,174] - onBaseAppShutDown: state=1
  INFO root [0x00002368] [2018-05-27 12:02:56,174] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002368] [2018-05-27 12:02:56,174] - onBaseAppShutDown: state=2
 DEBUG root [0x00002368] [2018-05-27 12:02:56,182] - Halls::~Halls(): 2001
 DEBUG root [0x00002368] [2018-05-27 12:02:56,183] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002368] [2018-05-27 12:02:56,183] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002368] [2018-05-27 12:02:56,183] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002368] [2018-05-27 12:02:56,183] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002368] [2018-05-27 12:02:56,184] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002368] [2018-05-27 12:02:56,184] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002368] [2018-05-27 12:02:56,184] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002368] [2018-05-27 12:02:56,184] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002368] [2018-05-27 12:02:56,194] - Script::uninstall(): is successfully!
 DEBUG root [0x00002368] [2018-05-27 12:02:56,194] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002db0] [2018-05-27 12:02:57,393] - 
  INFO root [0x00002db0] [2018-05-27 12:02:57,394] - -----------------------------------------------------------------------------------------


  INFO root [0x00002db0] [2018-05-27 12:02:57,395] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002db0] [2018-05-27 12:02:57,395] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002db0] [2018-05-27 12:02:57,395] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002db0] [2018-05-27 12:02:57,398] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00002db0] [2018-05-27 12:02:57,398] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00002db0] [2018-05-27 12:02:57,400] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51259 )
  INFO root [0x00002db0] [2018-05-27 12:02:57,400] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51259, SOMAXCONN=128.
  INFO root [0x00002db0] [2018-05-27 12:02:57,400] - server-configs:
  INFO root [0x00002db0] [2018-05-27 12:02:57,400] - 	gameUpdateHertz : 10
  INFO root [0x00002db0] [2018-05-27 12:02:57,400] - 	entryScriptFile : kbemain
  INFO root [0x00002db0] [2018-05-27 12:02:57,400] - 	internalAddr : 192.168.0.104:51259
  INFO root [0x00002db0] [2018-05-27 12:02:57,400] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00002db0] [2018-05-27 12:02:57,401] - 	componentID : 7001
  INFO root [0x00002db0] [2018-05-27 12:02:59,128] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 11528. PID: 12400 ----
  INFO root [0x00002db0] [2018-05-27 12:02:59,128] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002db0] [2018-05-27 12:02:59,129] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002db0] [2018-05-27 12:02:59,129] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,254] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,254] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,254] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,257] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,258] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,258] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,258] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,294] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002db0] [2018-05-27 12:02:59,327] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002db0] [2018-05-27 12:02:59,328] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,344] - loaded entity-script:Account(1).
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,345] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,351] - loaded entity-script:Halls(3).
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,352] - loaded entity-script:Room(4).
  INFO root [0x00002db0] [2018-05-27 12:02:59,352] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002db0] [2018-05-27 12:02:59,352] - TelnetServer server is running on port 40000
  INFO root [0x00002db0] [2018-05-27 12:02:59,667] - ---- baseapp is running ----
 DEBUG root [0x00002db0] [2018-05-27 12:02:59,667] - Components::process(): Request for the process of identity...
  INFO root [0x00003a70] [2018-05-27 12:03:02,099] - 
  INFO root [0x00003a70] [2018-05-27 12:03:02,101] - -----------------------------------------------------------------------------------------


  INFO root [0x00003a70] [2018-05-27 12:03:02,102] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003a70] [2018-05-27 12:03:02,102] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003a70] [2018-05-27 12:03:02,102] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003a70] [2018-05-27 12:03:02,112] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00003a70] [2018-05-27 12:03:02,112] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00003a70] [2018-05-27 12:03:02,113] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51277 )
  INFO root [0x00003a70] [2018-05-27 12:03:02,114] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51277, SOMAXCONN=128.
  INFO root [0x00003a70] [2018-05-27 12:03:02,114] - server-configs:
  INFO root [0x00003a70] [2018-05-27 12:03:02,114] - 	gameUpdateHertz : 10
  INFO root [0x00003a70] [2018-05-27 12:03:02,114] - 	entryScriptFile : kbemain
  INFO root [0x00003a70] [2018-05-27 12:03:02,114] - 	internalAddr : 192.168.0.104:51277
  INFO root [0x00003a70] [2018-05-27 12:03:02,114] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00003a70] [2018-05-27 12:03:02,115] - 	componentID : 7001
  INFO root [0x00003a70] [2018-05-27 12:03:03,822] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 11544. PID: 14956 ----
  INFO root [0x00003a70] [2018-05-27 12:03:03,823] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003a70] [2018-05-27 12:03:03,823] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003a70] [2018-05-27 12:03:03,823] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,948] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,948] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,949] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,952] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,952] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,952] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,953] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003a70] [2018-05-27 12:03:03,981] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003a70] [2018-05-27 12:03:04,009] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003a70] [2018-05-27 12:03:04,009] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003a70] [2018-05-27 12:03:04,023] - loaded entity-script:Account(1).
 DEBUG root [0x00003a70] [2018-05-27 12:03:04,024] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003a70] [2018-05-27 12:03:04,029] - loaded entity-script:Halls(3).
 DEBUG root [0x00003a70] [2018-05-27 12:03:04,030] - loaded entity-script:Room(4).
  INFO root [0x00003a70] [2018-05-27 12:03:04,031] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003a70] [2018-05-27 12:03:04,031] - TelnetServer server is running on port 40000
  INFO root [0x00003a70] [2018-05-27 12:03:04,314] - ---- baseapp is running ----
 DEBUG root [0x00003a70] [2018-05-27 12:03:04,315] - Components::process(): Request for the process of identity...
  WARN root [0x00003a70] [2018-05-27 12:03:10,395] - EntityApp::checkTickPeriod: tick took 6081% (6.08 seconds)!
  INFO root [0x00003a70] [2018-05-27 12:03:11,509] - Components::findComponents: find logger(1)...
  INFO root [0x00003a70] [2018-05-27 12:03:11,522] - Components::findComponents: found logger, addr:192.168.0.104:51278
  INFO root [0x00003a70] [2018-05-27 12:03:11,522] - Components::addComponent: reset orderLog, uid=11544!
  INFO root [0x00003a70] [2018-05-27 12:03:11,522] - Components::addComponent[logger], uid=11544, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003a70] [2018-05-27 12:03:11,523] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003a70] [2018-05-27 12:03:11,627] - Components::findComponents: found dbmgr, addr:192.168.0.104:51271
  INFO root [0x00003a70] [2018-05-27 12:03:11,627] - Components::addComponent: reset orderLog, uid=11544!
  INFO root [0x00003a70] [2018-05-27 12:03:11,628] - Components::addComponent[dbmgr], uid=11544, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003a70] [2018-05-27 12:03:11,628] - Components::findComponents: found dbmgr, addr:192.168.0.104:51271
  WARN root [0x00003a70] [2018-05-27 12:03:12,629] - Forwarding logs to logger[192.168.0.104:51278/0/0/0]...
 ERROR root [0x00003a70] [2018-05-27 12:03:31,224] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003a70] [2018-05-27 12:03:31,236] - The following logs sent to logger failed:
  WARN root [0x00003a70] [2018-05-27 12:03:31,236] - ==> [2018-05-27 12:03:31 218] TCPPacketReceiver::processPendingEvents(192.168.0.104:51278): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a70] [2018-05-27 12:03:31,236] - ==> [2018-05-27 12:03:31 224] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003a70] [2018-05-27 12:03:31,283] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51271): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003a70] [2018-05-27 12:03:31,284] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003a70] [2018-05-27 12:03:31,300] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003a70] [2018-05-27 12:03:31,301] - onBaseAppShutDown: state=0
  INFO root [0x00003a70] [2018-05-27 12:03:31,301] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003a70] [2018-05-27 12:03:31,301] - onBaseAppShutDown: state=1
  INFO root [0x00003a70] [2018-05-27 12:03:31,301] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003a70] [2018-05-27 12:03:31,301] - onBaseAppShutDown: state=2
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,309] - Halls::~Halls(): 2001
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,310] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,310] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,310] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,310] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,310] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,310] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,310] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,311] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003a70] [2018-05-27 12:03:31,320] - Script::uninstall(): is successfully!
 DEBUG root [0x00003a70] [2018-05-27 12:03:31,321] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000030ec] [2018-05-27 12:03:32,486] - 
  INFO root [0x000030ec] [2018-05-27 12:03:32,487] - -----------------------------------------------------------------------------------------


  INFO root [0x000030ec] [2018-05-27 12:03:32,488] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000030ec] [2018-05-27 12:03:32,488] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000030ec] [2018-05-27 12:03:32,488] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000030ec] [2018-05-27 12:03:32,492] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x000030ec] [2018-05-27 12:03:32,492] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x000030ec] [2018-05-27 12:03:32,494] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51312 )
  INFO root [0x000030ec] [2018-05-27 12:03:32,494] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51312, SOMAXCONN=128.
  INFO root [0x000030ec] [2018-05-27 12:03:32,495] - server-configs:
  INFO root [0x000030ec] [2018-05-27 12:03:32,495] - 	gameUpdateHertz : 10
  INFO root [0x000030ec] [2018-05-27 12:03:32,495] - 	entryScriptFile : kbemain
  INFO root [0x000030ec] [2018-05-27 12:03:32,495] - 	internalAddr : 192.168.0.104:51312
  INFO root [0x000030ec] [2018-05-27 12:03:32,495] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x000030ec] [2018-05-27 12:03:32,495] - 	componentID : 7001
  WARN root [0x000030ec] [2018-05-27 12:03:33,010] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20887, errorno=10048
  INFO root [0x000030ec] [2018-05-27 12:03:33,014] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 11646. PID: 14548 ----
  INFO root [0x000030ec] [2018-05-27 12:03:33,014] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000030ec] [2018-05-27 12:03:33,015] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000030ec] [2018-05-27 12:03:33,015] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,142] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,143] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,144] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,148] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,148] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,148] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,149] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,180] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000030ec] [2018-05-27 12:03:33,209] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000030ec] [2018-05-27 12:03:33,209] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,223] - loaded entity-script:Account(1).
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,224] - loaded entity-script:CheckName(2).
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,229] - loaded entity-script:Halls(3).
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,230] - loaded entity-script:Room(4).
  INFO root [0x000030ec] [2018-05-27 12:03:33,230] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000030ec] [2018-05-27 12:03:33,230] - TelnetServer server is running on port 40000
  INFO root [0x000030ec] [2018-05-27 12:03:33,519] - ---- baseapp is running ----
 DEBUG root [0x000030ec] [2018-05-27 12:03:33,519] - Components::process(): Request for the process of identity...
  WARN root [0x000030ec] [2018-05-27 12:03:39,573] - EntityApp::checkTickPeriod: tick took 6053% (6.05 seconds)!
  INFO root [0x000030ec] [2018-05-27 12:03:40,592] - Components::findComponents: find logger(1)...
  INFO root [0x000030ec] [2018-05-27 12:03:40,614] - Components::findComponents: found logger, addr:192.168.0.104:51311
  INFO root [0x000030ec] [2018-05-27 12:03:40,615] - Components::addComponent: reset orderLog, uid=11646!
  INFO root [0x000030ec] [2018-05-27 12:03:40,615] - Components::addComponent[logger], uid=11646, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000030ec] [2018-05-27 12:03:40,616] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000030ec] [2018-05-27 12:03:40,718] - Components::findComponents: found dbmgr, addr:192.168.0.104:51308
  INFO root [0x000030ec] [2018-05-27 12:03:40,719] - Components::addComponent: reset orderLog, uid=11646!
  INFO root [0x000030ec] [2018-05-27 12:03:40,719] - Components::addComponent[dbmgr], uid=11646, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000030ec] [2018-05-27 12:03:40,719] - Components::findComponents: found dbmgr, addr:192.168.0.104:51308
  WARN root [0x000030ec] [2018-05-27 12:03:41,719] - Forwarding logs to logger[192.168.0.104:51311/0/0/0]...
 ERROR root [0x000030ec] [2018-05-27 12:16:31,422] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000030ec] [2018-05-27 12:16:31,429] - The following logs sent to logger failed:
  WARN root [0x000030ec] [2018-05-27 12:16:31,430] - ==> [2018-05-27 12:16:31 416] TCPPacketReceiver::processPendingEvents(192.168.0.104:51311): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000030ec] [2018-05-27 12:16:31,430] - ==> [2018-05-27 12:16:31 422] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000030ec] [2018-05-27 12:16:31,482] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51308): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000030ec] [2018-05-27 12:16:31,485] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000030ec] [2018-05-27 12:16:31,494] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000030ec] [2018-05-27 12:16:31,497] - onBaseAppShutDown: state=0
  INFO root [0x000030ec] [2018-05-27 12:16:31,497] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000030ec] [2018-05-27 12:16:31,497] - onBaseAppShutDown: state=1
  INFO root [0x000030ec] [2018-05-27 12:16:31,497] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000030ec] [2018-05-27 12:16:31,497] - onBaseAppShutDown: state=2
 ERROR root [0x000030ec] [2018-05-27 12:16:31,505] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000030ec] [2018-05-27 12:16:31,506] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,506] - Account::~Account(): 2
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,506] - Room::~Room(): 3
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,507] - Halls::~Halls(): 1
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,507] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,507] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,507] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,507] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,508] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,508] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,508] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,508] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000030ec] [2018-05-27 12:16:31,518] - Script::uninstall(): is successfully!
 DEBUG root [0x000030ec] [2018-05-27 12:16:31,518] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000030c8] [2018-05-27 12:16:32,672] - 
  INFO root [0x000030c8] [2018-05-27 12:16:32,675] - -----------------------------------------------------------------------------------------


  INFO root [0x000030c8] [2018-05-27 12:16:32,676] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000030c8] [2018-05-27 12:16:32,676] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000030c8] [2018-05-27 12:16:32,676] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000030c8] [2018-05-27 12:16:32,682] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x000030c8] [2018-05-27 12:16:32,682] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x000030c8] [2018-05-27 12:16:32,684] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51480 )
  INFO root [0x000030c8] [2018-05-27 12:16:32,684] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51480, SOMAXCONN=128.
  INFO root [0x000030c8] [2018-05-27 12:16:32,685] - server-configs:
  INFO root [0x000030c8] [2018-05-27 12:16:32,685] - 	gameUpdateHertz : 10
  INFO root [0x000030c8] [2018-05-27 12:16:32,685] - 	entryScriptFile : kbemain
  INFO root [0x000030c8] [2018-05-27 12:16:32,685] - 	internalAddr : 192.168.0.104:51480
  INFO root [0x000030c8] [2018-05-27 12:16:32,685] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x000030c8] [2018-05-27 12:16:32,685] - 	componentID : 7001
  INFO root [0x000030c8] [2018-05-27 12:16:34,410] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 14193. PID: 7540 ----
  INFO root [0x000030c8] [2018-05-27 12:16:34,411] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000030c8] [2018-05-27 12:16:34,412] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000030c8] [2018-05-27 12:16:34,412] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,534] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,535] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,535] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,538] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,538] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,538] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,539] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,566] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000030c8] [2018-05-27 12:16:34,593] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000030c8] [2018-05-27 12:16:34,593] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,612] - loaded entity-script:Account(1).
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,613] - loaded entity-script:CheckName(2).
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,618] - loaded entity-script:Halls(3).
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,620] - loaded entity-script:Room(4).
  INFO root [0x000030c8] [2018-05-27 12:16:34,620] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000030c8] [2018-05-27 12:16:34,620] - TelnetServer server is running on port 40000
  INFO root [0x000030c8] [2018-05-27 12:16:34,898] - ---- baseapp is running ----
 DEBUG root [0x000030c8] [2018-05-27 12:16:34,898] - Components::process(): Request for the process of identity...
  WARN root [0x000030c8] [2018-05-27 12:16:40,962] - EntityApp::checkTickPeriod: tick took 6063% (6.06 seconds)!
  INFO root [0x000030c8] [2018-05-27 12:16:41,980] - Components::findComponents: find logger(1)...
  INFO root [0x000030c8] [2018-05-27 12:16:42,032] - Components::findComponents: found logger, addr:192.168.0.104:51487
  INFO root [0x000030c8] [2018-05-27 12:16:42,033] - Components::addComponent: reset orderLog, uid=14193!
  INFO root [0x000030c8] [2018-05-27 12:16:42,033] - Components::addComponent[logger], uid=14193, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000030c8] [2018-05-27 12:16:42,034] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000030c8] [2018-05-27 12:16:42,135] - Components::findComponents: found dbmgr, addr:192.168.0.104:51482
  INFO root [0x000030c8] [2018-05-27 12:16:42,136] - Components::addComponent: reset orderLog, uid=14193!
  INFO root [0x000030c8] [2018-05-27 12:16:42,136] - Components::addComponent[dbmgr], uid=14193, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000030c8] [2018-05-27 12:16:42,136] - Components::findComponents: found dbmgr, addr:192.168.0.104:51482
  WARN root [0x000030c8] [2018-05-27 12:16:43,136] - Forwarding logs to logger[192.168.0.104:51487/0/0/0]...
 ERROR root [0x000030c8] [2018-05-27 12:42:17,790] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000030c8] [2018-05-27 12:42:17,800] - The following logs sent to logger failed:
  WARN root [0x000030c8] [2018-05-27 12:42:17,800] - ==> [2018-05-27 12:42:17 787] TCPPacketReceiver::processPendingEvents(192.168.0.104:51487): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000030c8] [2018-05-27 12:42:17,800] - ==> [2018-05-27 12:42:17 790] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000030c8] [2018-05-27 12:42:17,850] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51482): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000030c8] [2018-05-27 12:42:17,854] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000030c8] [2018-05-27 12:42:17,860] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000030c8] [2018-05-27 12:42:17,861] - onBaseAppShutDown: state=0
  INFO root [0x000030c8] [2018-05-27 12:42:17,861] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000030c8] [2018-05-27 12:42:17,861] - onBaseAppShutDown: state=1
  INFO root [0x000030c8] [2018-05-27 12:42:17,861] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000030c8] [2018-05-27 12:42:17,861] - onBaseAppShutDown: state=2
 ERROR root [0x000030c8] [2018-05-27 12:42:17,869] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000030c8] [2018-05-27 12:42:17,870] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000030c8] [2018-05-27 12:42:17,870] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x000030c8] [2018-05-27 12:42:17,872] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,874] - Account::~Account(): 2002
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,874] - Room::~Room(): 2003
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,874] - Account::~Account(): 2004
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,875] - Room::~Room(): 2005
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,875] - Halls::~Halls(): 2001
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,875] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,876] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,876] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,876] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,876] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,876] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,876] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,876] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000030c8] [2018-05-27 12:42:17,886] - Script::uninstall(): is successfully!
 DEBUG root [0x000030c8] [2018-05-27 12:42:17,886] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003288] [2018-05-27 12:42:19,097] - 
  INFO root [0x00003288] [2018-05-27 12:42:19,097] - -----------------------------------------------------------------------------------------


  INFO root [0x00003288] [2018-05-27 12:42:19,098] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003288] [2018-05-27 12:42:19,098] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003288] [2018-05-27 12:42:19,099] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003288] [2018-05-27 12:42:19,101] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00003288] [2018-05-27 12:42:19,101] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00003288] [2018-05-27 12:42:19,103] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51763 )
  INFO root [0x00003288] [2018-05-27 12:42:19,103] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51763, SOMAXCONN=128.
  INFO root [0x00003288] [2018-05-27 12:42:19,103] - server-configs:
  INFO root [0x00003288] [2018-05-27 12:42:19,103] - 	gameUpdateHertz : 10
  INFO root [0x00003288] [2018-05-27 12:42:19,103] - 	entryScriptFile : kbemain
  INFO root [0x00003288] [2018-05-27 12:42:19,104] - 	internalAddr : 192.168.0.104:51763
  INFO root [0x00003288] [2018-05-27 12:42:19,104] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00003288] [2018-05-27 12:42:19,104] - 	componentID : 7001
  INFO root [0x00003288] [2018-05-27 12:42:20,826] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 19241. PID: 5644 ----
  INFO root [0x00003288] [2018-05-27 12:42:20,826] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003288] [2018-05-27 12:42:20,827] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003288] [2018-05-27 12:42:20,827] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003288] [2018-05-27 12:42:20,953] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003288] [2018-05-27 12:42:20,953] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003288] [2018-05-27 12:42:20,954] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003288] [2018-05-27 12:42:20,958] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003288] [2018-05-27 12:42:20,958] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003288] [2018-05-27 12:42:20,959] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003288] [2018-05-27 12:42:20,959] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003288] [2018-05-27 12:42:20,987] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003288] [2018-05-27 12:42:21,015] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003288] [2018-05-27 12:42:21,016] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003288] [2018-05-27 12:42:21,029] - loaded entity-script:Account(1).
 DEBUG root [0x00003288] [2018-05-27 12:42:21,031] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003288] [2018-05-27 12:42:21,037] - loaded entity-script:Halls(3).
 DEBUG root [0x00003288] [2018-05-27 12:42:21,038] - loaded entity-script:Room(4).
  INFO root [0x00003288] [2018-05-27 12:42:21,038] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003288] [2018-05-27 12:42:21,038] - TelnetServer server is running on port 40000
  INFO root [0x00003288] [2018-05-27 12:42:21,338] - ---- baseapp is running ----
 DEBUG root [0x00003288] [2018-05-27 12:42:21,338] - Components::process(): Request for the process of identity...
  WARN root [0x00003288] [2018-05-27 12:42:27,395] - EntityApp::checkTickPeriod: tick took 6057% (6.06 seconds)!
  INFO root [0x00003288] [2018-05-27 12:42:28,438] - Components::findComponents: find logger(1)...
  INFO root [0x00003288] [2018-05-27 12:42:28,480] - Components::findComponents: found logger, addr:192.168.0.104:51759
  INFO root [0x00003288] [2018-05-27 12:42:28,481] - Components::addComponent: reset orderLog, uid=19241!
  INFO root [0x00003288] [2018-05-27 12:42:28,481] - Components::addComponent[logger], uid=19241, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003288] [2018-05-27 12:42:28,482] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003288] [2018-05-27 12:42:28,586] - Components::findComponents: found dbmgr, addr:192.168.0.104:51758
  INFO root [0x00003288] [2018-05-27 12:42:28,586] - Components::addComponent: reset orderLog, uid=19241!
  INFO root [0x00003288] [2018-05-27 12:42:28,587] - Components::addComponent[dbmgr], uid=19241, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003288] [2018-05-27 12:42:28,587] - Components::findComponents: found dbmgr, addr:192.168.0.104:51758
  WARN root [0x00003288] [2018-05-27 12:42:29,587] - EntityApp::checkTickPeriod: tick took 1249% (1.25 seconds)!
  WARN root [0x00003288] [2018-05-27 12:42:29,588] - Forwarding logs to logger[192.168.0.104:51759/0/0/0]...
 ERROR root [0x00003288] [2018-05-27 12:47:28,192] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00003288] [2018-05-27 12:47:28,205] - The following logs sent to logger failed:
  WARN root [0x00003288] [2018-05-27 12:47:28,205] - ==> [2018-05-27 12:47:28 190] TCPPacketReceiver::processPendingEvents(192.168.0.104:51759): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003288] [2018-05-27 12:47:28,206] - ==> [2018-05-27 12:47:28 193] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00003288] [2018-05-27 12:47:28,260] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51758): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003288] [2018-05-27 12:47:28,269] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00003288] [2018-05-27 12:47:28,278] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003288] [2018-05-27 12:47:28,281] - onBaseAppShutDown: state=0
  INFO root [0x00003288] [2018-05-27 12:47:28,281] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003288] [2018-05-27 12:47:28,281] - onBaseAppShutDown: state=1
  INFO root [0x00003288] [2018-05-27 12:47:28,281] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003288] [2018-05-27 12:47:28,282] - onBaseAppShutDown: state=2
 ERROR root [0x00003288] [2018-05-27 12:47:28,290] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00003288] [2018-05-27 12:47:28,290] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003288] [2018-05-27 12:47:28,291] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00003288] [2018-05-27 12:47:28,291] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003288] [2018-05-27 12:47:28,292] - Account::onCellWriteToDBCompleted(2006): not found dbmgr!
 ERROR root [0x00003288] [2018-05-27 12:47:28,292] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003288] [2018-05-27 12:47:28,292] - CheckName::onCellWriteToDBCompleted(2007): not found dbmgr!
 ERROR root [0x00003288] [2018-05-27 12:47:28,292] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003288] [2018-05-27 12:47:28,293] - CheckName::~CheckName(): 2007
 DEBUG root [0x00003288] [2018-05-27 12:47:28,293] - Account::~Account(): 2004
 DEBUG root [0x00003288] [2018-05-27 12:47:28,293] - Room::~Room(): 2005
 DEBUG root [0x00003288] [2018-05-27 12:47:28,293] - Account::~Account(): 2006
 DEBUG root [0x00003288] [2018-05-27 12:47:28,293] - Room::~Room(): 2008
 DEBUG root [0x00003288] [2018-05-27 12:47:28,294] - Account::~Account(): 2002
 DEBUG root [0x00003288] [2018-05-27 12:47:28,294] - Room::~Room(): 2003
 DEBUG root [0x00003288] [2018-05-27 12:47:28,294] - Halls::~Halls(): 2001
 DEBUG root [0x00003288] [2018-05-27 12:47:28,294] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003288] [2018-05-27 12:47:28,295] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00003288] [2018-05-27 12:47:28,295] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00003288] [2018-05-27 12:47:28,295] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003288] [2018-05-27 12:47:28,295] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00003288] [2018-05-27 12:47:28,295] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003288] [2018-05-27 12:47:28,295] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003288] [2018-05-27 12:47:28,295] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00003288] [2018-05-27 12:47:28,307] - Script::uninstall(): is successfully!
 DEBUG root [0x00003288] [2018-05-27 12:47:28,307] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002360] [2018-05-27 12:47:29,491] - 
  INFO root [0x00002360] [2018-05-27 12:47:29,493] - -----------------------------------------------------------------------------------------


  INFO root [0x00002360] [2018-05-27 12:47:29,494] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00002360] [2018-05-27 12:47:29,494] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00002360] [2018-05-27 12:47:29,494] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00002360] [2018-05-27 12:47:29,499] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00002360] [2018-05-27 12:47:29,500] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51844 )
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51844, SOMAXCONN=128.
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - server-configs:
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - 	gameUpdateHertz : 10
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - 	entryScriptFile : kbemain
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - 	internalAddr : 192.168.0.104:51844
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00002360] [2018-05-27 12:47:29,501] - 	componentID : 7001
  INFO root [0x00002360] [2018-05-27 12:47:31,212] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 20257. PID: 12348 ----
  INFO root [0x00002360] [2018-05-27 12:47:31,212] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00002360] [2018-05-27 12:47:31,213] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002360] [2018-05-27 12:47:31,213] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002360] [2018-05-27 12:47:31,341] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002360] [2018-05-27 12:47:31,342] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002360] [2018-05-27 12:47:31,342] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002360] [2018-05-27 12:47:31,347] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002360] [2018-05-27 12:47:31,347] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002360] [2018-05-27 12:47:31,347] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002360] [2018-05-27 12:47:31,348] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002360] [2018-05-27 12:47:31,385] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002360] [2018-05-27 12:47:31,416] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00002360] [2018-05-27 12:47:31,416] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002360] [2018-05-27 12:47:31,438] - loaded entity-script:Account(1).
 DEBUG root [0x00002360] [2018-05-27 12:47:31,439] - loaded entity-script:CheckName(2).
 DEBUG root [0x00002360] [2018-05-27 12:47:31,445] - loaded entity-script:Halls(3).
 DEBUG root [0x00002360] [2018-05-27 12:47:31,451] - loaded entity-script:Room(4).
  INFO root [0x00002360] [2018-05-27 12:47:31,451] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002360] [2018-05-27 12:47:31,451] - TelnetServer server is running on port 40000
  INFO root [0x00002360] [2018-05-27 12:47:31,778] - ---- baseapp is running ----
 DEBUG root [0x00002360] [2018-05-27 12:47:31,778] - Components::process(): Request for the process of identity...
  WARN root [0x00002360] [2018-05-27 12:47:32,089] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20992, errorno=10048
  WARN root [0x00002360] [2018-05-27 12:47:38,204] - EntityApp::checkTickPeriod: tick took 6424% (6.42 seconds)!
  INFO root [0x00002360] [2018-05-27 12:47:39,280] - Components::findComponents: find logger(1)...
  INFO root [0x00002360] [2018-05-27 12:47:39,328] - Components::findComponents: found logger, addr:192.168.0.104:51850
  INFO root [0x00002360] [2018-05-27 12:47:39,328] - Components::addComponent: reset orderLog, uid=20257!
  INFO root [0x00002360] [2018-05-27 12:47:39,329] - Components::addComponent[logger], uid=20257, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002360] [2018-05-27 12:47:39,331] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002360] [2018-05-27 12:47:39,434] - Components::findComponents: found dbmgr, addr:192.168.0.104:51843
  INFO root [0x00002360] [2018-05-27 12:47:39,435] - Components::addComponent: reset orderLog, uid=20257!
  INFO root [0x00002360] [2018-05-27 12:47:39,435] - Components::addComponent[dbmgr], uid=20257, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002360] [2018-05-27 12:47:39,436] - Components::findComponents: found dbmgr, addr:192.168.0.104:51843
  WARN root [0x00002360] [2018-05-27 12:47:40,436] - EntityApp::checkTickPeriod: tick took 1256% (1.26 seconds)!
  WARN root [0x00002360] [2018-05-27 12:47:40,437] - Forwarding logs to logger[192.168.0.104:51850/0/0/0]...
 ERROR root [0x00002360] [2018-05-27 12:52:43,207] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002360] [2018-05-27 12:52:43,221] - The following logs sent to logger failed:
  WARN root [0x00002360] [2018-05-27 12:52:43,221] - ==> [2018-05-27 12:52:43 204] TCPPacketReceiver::processPendingEvents(192.168.0.104:51850): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002360] [2018-05-27 12:52:43,221] - ==> [2018-05-27 12:52:43 207] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002360] [2018-05-27 12:52:43,277] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51843): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002360] [2018-05-27 12:52:43,280] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002360] [2018-05-27 12:52:43,295] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002360] [2018-05-27 12:52:43,295] - onBaseAppShutDown: state=0
  INFO root [0x00002360] [2018-05-27 12:52:43,295] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002360] [2018-05-27 12:52:43,295] - onBaseAppShutDown: state=1
  INFO root [0x00002360] [2018-05-27 12:52:43,295] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002360] [2018-05-27 12:52:43,295] - onBaseAppShutDown: state=2
 ERROR root [0x00002360] [2018-05-27 12:52:43,304] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00002360] [2018-05-27 12:52:43,304] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002360] [2018-05-27 12:52:43,305] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00002360] [2018-05-27 12:52:43,306] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002360] [2018-05-27 12:52:43,307] - Account::~Account(): 2002
 DEBUG root [0x00002360] [2018-05-27 12:52:43,307] - Room::~Room(): 2003
 DEBUG root [0x00002360] [2018-05-27 12:52:43,307] - Account::~Account(): 2004
 DEBUG root [0x00002360] [2018-05-27 12:52:43,307] - Room::~Room(): 2005
 DEBUG root [0x00002360] [2018-05-27 12:52:43,307] - Halls::~Halls(): 2001
 DEBUG root [0x00002360] [2018-05-27 12:52:43,308] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002360] [2018-05-27 12:52:43,308] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002360] [2018-05-27 12:52:43,308] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002360] [2018-05-27 12:52:43,308] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002360] [2018-05-27 12:52:43,308] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002360] [2018-05-27 12:52:43,309] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002360] [2018-05-27 12:52:43,309] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002360] [2018-05-27 12:52:43,309] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002360] [2018-05-27 12:52:43,317] - Script::uninstall(): is successfully!
 DEBUG root [0x00002360] [2018-05-27 12:52:43,317] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001804] [2018-05-27 12:52:44,536] - 
  INFO root [0x00001804] [2018-05-27 12:52:44,536] - -----------------------------------------------------------------------------------------


  INFO root [0x00001804] [2018-05-27 12:52:44,537] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001804] [2018-05-27 12:52:44,537] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001804] [2018-05-27 12:52:44,537] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001804] [2018-05-27 12:52:44,540] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00001804] [2018-05-27 12:52:44,540] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00001804] [2018-05-27 12:52:44,541] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:51909 )
  INFO root [0x00001804] [2018-05-27 12:52:44,541] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:51909, SOMAXCONN=128.
  INFO root [0x00001804] [2018-05-27 12:52:44,541] - server-configs:
  INFO root [0x00001804] [2018-05-27 12:52:44,541] - 	gameUpdateHertz : 10
  INFO root [0x00001804] [2018-05-27 12:52:44,541] - 	entryScriptFile : kbemain
  INFO root [0x00001804] [2018-05-27 12:52:44,542] - 	internalAddr : 192.168.0.104:51909
  INFO root [0x00001804] [2018-05-27 12:52:44,542] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00001804] [2018-05-27 12:52:44,542] - 	componentID : 7001
  INFO root [0x00001804] [2018-05-27 12:52:46,263] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 21286. PID: 15296 ----
  INFO root [0x00001804] [2018-05-27 12:52:46,264] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001804] [2018-05-27 12:52:46,264] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001804] [2018-05-27 12:52:46,264] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001804] [2018-05-27 12:52:46,387] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001804] [2018-05-27 12:52:46,388] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001804] [2018-05-27 12:52:46,388] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001804] [2018-05-27 12:52:46,391] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001804] [2018-05-27 12:52:46,391] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001804] [2018-05-27 12:52:46,391] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001804] [2018-05-27 12:52:46,392] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001804] [2018-05-27 12:52:46,420] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001804] [2018-05-27 12:52:46,448] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001804] [2018-05-27 12:52:46,448] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001804] [2018-05-27 12:52:46,461] - loaded entity-script:Account(1).
 DEBUG root [0x00001804] [2018-05-27 12:52:46,462] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001804] [2018-05-27 12:52:46,467] - loaded entity-script:Halls(3).
 DEBUG root [0x00001804] [2018-05-27 12:52:46,474] - loaded entity-script:Room(4).
  INFO root [0x00001804] [2018-05-27 12:52:46,474] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001804] [2018-05-27 12:52:46,475] - TelnetServer server is running on port 40000
  INFO root [0x00001804] [2018-05-27 12:52:46,752] - ---- baseapp is running ----
 DEBUG root [0x00001804] [2018-05-27 12:52:46,752] - Components::process(): Request for the process of identity...
  WARN root [0x00001804] [2018-05-27 12:52:52,849] - EntityApp::checkTickPeriod: tick took 6096% (6.10 seconds)!
  INFO root [0x00001804] [2018-05-27 12:52:53,939] - Components::findComponents: find logger(1)...
  INFO root [0x00001804] [2018-05-27 12:52:54,004] - Components::findComponents: found logger, addr:192.168.0.104:51907
  INFO root [0x00001804] [2018-05-27 12:52:54,005] - Components::addComponent: reset orderLog, uid=21286!
  INFO root [0x00001804] [2018-05-27 12:52:54,006] - Components::addComponent[logger], uid=21286, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001804] [2018-05-27 12:52:54,008] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001804] [2018-05-27 12:52:54,107] - Components::findComponents: found dbmgr, addr:192.168.0.104:51905
  INFO root [0x00001804] [2018-05-27 12:52:54,107] - Components::addComponent: reset orderLog, uid=21286!
  INFO root [0x00001804] [2018-05-27 12:52:54,108] - Components::addComponent[dbmgr], uid=21286, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001804] [2018-05-27 12:52:54,108] - Components::findComponents: found dbmgr, addr:192.168.0.104:51905
  WARN root [0x00001804] [2018-05-27 12:52:55,108] - Forwarding logs to logger[192.168.0.104:51907/0/0/0]...
 ERROR root [0x00001804] [2018-05-27 13:02:37,466] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001804] [2018-05-27 13:02:37,473] - The following logs sent to logger failed:
  WARN root [0x00001804] [2018-05-27 13:02:37,473] - ==> [2018-05-27 13:02:37 457] TCPPacketReceiver::processPendingEvents(192.168.0.104:51907): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001804] [2018-05-27 13:02:37,473] - ==> [2018-05-27 13:02:37 466] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001804] [2018-05-27 13:02:37,525] - TCPPacketReceiver::processPendingEvents(192.168.0.104:51905): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001804] [2018-05-27 13:02:37,534] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001804] [2018-05-27 13:02:37,539] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001804] [2018-05-27 13:02:37,541] - onBaseAppShutDown: state=0
  INFO root [0x00001804] [2018-05-27 13:02:37,541] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001804] [2018-05-27 13:02:37,541] - onBaseAppShutDown: state=1
  INFO root [0x00001804] [2018-05-27 13:02:37,541] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001804] [2018-05-27 13:02:37,541] - onBaseAppShutDown: state=2
 ERROR root [0x00001804] [2018-05-27 13:02:37,549] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00001804] [2018-05-27 13:02:37,553] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001804] [2018-05-27 13:02:37,553] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00001804] [2018-05-27 13:02:37,554] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001804] [2018-05-27 13:02:37,555] - Account::~Account(): 2002
 DEBUG root [0x00001804] [2018-05-27 13:02:37,555] - Account::~Account(): 2004
 DEBUG root [0x00001804] [2018-05-27 13:02:37,555] - Room::~Room(): 2003
 DEBUG root [0x00001804] [2018-05-27 13:02:37,555] - Halls::~Halls(): 2001
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001804] [2018-05-27 13:02:37,556] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001804] [2018-05-27 13:02:37,566] - Script::uninstall(): is successfully!
 DEBUG root [0x00001804] [2018-05-27 13:02:37,566] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001de0] [2018-05-27 13:02:38,766] - 
  INFO root [0x00001de0] [2018-05-27 13:02:38,766] - -----------------------------------------------------------------------------------------


  INFO root [0x00001de0] [2018-05-27 13:02:38,767] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00001de0] [2018-05-27 13:02:38,767] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00001de0] [2018-05-27 13:02:38,767] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00001de0] [2018-05-27 13:02:38,770] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00001de0] [2018-05-27 13:02:38,770] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00001de0] [2018-05-27 13:02:38,771] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52028 )
  INFO root [0x00001de0] [2018-05-27 13:02:38,772] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52028, SOMAXCONN=128.
  INFO root [0x00001de0] [2018-05-27 13:02:38,772] - server-configs:
  INFO root [0x00001de0] [2018-05-27 13:02:38,772] - 	gameUpdateHertz : 10
  INFO root [0x00001de0] [2018-05-27 13:02:38,772] - 	entryScriptFile : kbemain
  INFO root [0x00001de0] [2018-05-27 13:02:38,772] - 	internalAddr : 192.168.0.104:52028
  INFO root [0x00001de0] [2018-05-27 13:02:38,772] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00001de0] [2018-05-27 13:02:38,772] - 	componentID : 7001
  INFO root [0x00001de0] [2018-05-27 13:02:40,500] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 23225. PID: 15936 ----
  INFO root [0x00001de0] [2018-05-27 13:02:40,501] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00001de0] [2018-05-27 13:02:40,501] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001de0] [2018-05-27 13:02:40,502] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,626] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,626] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,627] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,630] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,631] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,631] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,631] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,659] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00001de0] [2018-05-27 13:02:40,688] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00001de0] [2018-05-27 13:02:40,688] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,703] - loaded entity-script:Account(1).
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,704] - loaded entity-script:CheckName(2).
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,715] - loaded entity-script:Halls(3).
 DEBUG root [0x00001de0] [2018-05-27 13:02:40,717] - loaded entity-script:Room(4).
  INFO root [0x00001de0] [2018-05-27 13:02:40,717] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001de0] [2018-05-27 13:02:40,717] - TelnetServer server is running on port 40000
  INFO root [0x00001de0] [2018-05-27 13:02:41,033] - ---- baseapp is running ----
 DEBUG root [0x00001de0] [2018-05-27 13:02:41,033] - Components::process(): Request for the process of identity...
  WARN root [0x00001de0] [2018-05-27 13:02:47,097] - EntityApp::checkTickPeriod: tick took 6063% (6.06 seconds)!
  INFO root [0x00001de0] [2018-05-27 13:02:48,134] - Components::findComponents: find logger(1)...
  INFO root [0x00001de0] [2018-05-27 13:02:48,158] - Components::findComponents: found logger, addr:192.168.0.104:52023
  INFO root [0x00001de0] [2018-05-27 13:02:48,159] - Components::addComponent: reset orderLog, uid=23225!
  INFO root [0x00001de0] [2018-05-27 13:02:48,159] - Components::addComponent[logger], uid=23225, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001de0] [2018-05-27 13:02:48,162] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00001de0] [2018-05-27 13:02:48,263] - Components::findComponents: found dbmgr, addr:192.168.0.104:52024
  INFO root [0x00001de0] [2018-05-27 13:02:48,264] - Components::addComponent: reset orderLog, uid=23225!
  INFO root [0x00001de0] [2018-05-27 13:02:48,264] - Components::addComponent[dbmgr], uid=23225, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001de0] [2018-05-27 13:02:48,264] - Components::findComponents: found dbmgr, addr:192.168.0.104:52024
  WARN root [0x00001de0] [2018-05-27 13:02:49,264] - EntityApp::checkTickPeriod: tick took 1230% (1.23 seconds)!
  WARN root [0x00001de0] [2018-05-27 13:02:49,266] - Forwarding logs to logger[192.168.0.104:52023/0/0/0]...
 ERROR root [0x00001de0] [2018-05-27 13:08:32,906] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00001de0] [2018-05-27 13:08:32,915] - The following logs sent to logger failed:
  WARN root [0x00001de0] [2018-05-27 13:08:32,916] - ==> [2018-05-27 13:08:32 899] TCPPacketReceiver::processPendingEvents(192.168.0.104:52023): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001de0] [2018-05-27 13:08:32,916] - ==> [2018-05-27 13:08:32 907] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00001de0] [2018-05-27 13:08:32,971] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52024): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001de0] [2018-05-27 13:08:32,973] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00001de0] [2018-05-27 13:08:32,986] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001de0] [2018-05-27 13:08:32,987] - onBaseAppShutDown: state=0
  INFO root [0x00001de0] [2018-05-27 13:08:32,987] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001de0] [2018-05-27 13:08:32,987] - onBaseAppShutDown: state=1
  INFO root [0x00001de0] [2018-05-27 13:08:32,987] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001de0] [2018-05-27 13:08:32,987] - onBaseAppShutDown: state=2
 ERROR root [0x00001de0] [2018-05-27 13:08:32,995] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00001de0] [2018-05-27 13:08:32,996] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001de0] [2018-05-27 13:08:32,996] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x00001de0] [2018-05-27 13:08:32,997] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,997] - Account::~Account(): 2002
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,997] - Account::~Account(): 2004
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,998] - Room::~Room(): 2003
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,998] - Halls::~Halls(): 2001
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,998] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,998] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,998] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,999] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,999] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,999] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,999] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00001de0] [2018-05-27 13:08:32,999] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00001de0] [2018-05-27 13:08:33,009] - Script::uninstall(): is successfully!
 DEBUG root [0x00001de0] [2018-05-27 13:08:33,010] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000113c] [2018-05-27 13:08:34,203] - 
  INFO root [0x0000113c] [2018-05-27 13:08:34,203] - -----------------------------------------------------------------------------------------


  INFO root [0x0000113c] [2018-05-27 13:08:34,204] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000113c] [2018-05-27 13:08:34,204] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000113c] [2018-05-27 13:08:34,204] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000113c] [2018-05-27 13:08:34,207] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x0000113c] [2018-05-27 13:08:34,208] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x0000113c] [2018-05-27 13:08:34,209] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52284 )
  INFO root [0x0000113c] [2018-05-27 13:08:34,209] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52284, SOMAXCONN=128.
  INFO root [0x0000113c] [2018-05-27 13:08:34,209] - server-configs:
  INFO root [0x0000113c] [2018-05-27 13:08:34,209] - 	gameUpdateHertz : 10
  INFO root [0x0000113c] [2018-05-27 13:08:34,209] - 	entryScriptFile : kbemain
  INFO root [0x0000113c] [2018-05-27 13:08:34,209] - 	internalAddr : 192.168.0.104:52284
  INFO root [0x0000113c] [2018-05-27 13:08:34,209] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x0000113c] [2018-05-27 13:08:34,210] - 	componentID : 7001
  INFO root [0x0000113c] [2018-05-27 13:08:35,904] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 24385. PID: 4212 ----
  INFO root [0x0000113c] [2018-05-27 13:08:35,905] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000113c] [2018-05-27 13:08:35,905] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000113c] [2018-05-27 13:08:35,905] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,028] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,028] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,029] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,032] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,032] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,032] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,033] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,061] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000113c] [2018-05-27 13:08:36,088] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000113c] [2018-05-27 13:08:36,088] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,105] - loaded entity-script:Account(1).
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,106] - loaded entity-script:CheckName(2).
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,125] - loaded entity-script:Halls(3).
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,127] - loaded entity-script:Room(4).
  INFO root [0x0000113c] [2018-05-27 13:08:36,127] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000113c] [2018-05-27 13:08:36,127] - TelnetServer server is running on port 40000
  INFO root [0x0000113c] [2018-05-27 13:08:36,459] - ---- baseapp is running ----
 DEBUG root [0x0000113c] [2018-05-27 13:08:36,459] - Components::process(): Request for the process of identity...
  WARN root [0x0000113c] [2018-05-27 13:08:39,803] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20035, errorno=10048
  WARN root [0x0000113c] [2018-05-27 13:08:42,868] - EntityApp::checkTickPeriod: tick took 6409% (6.41 seconds)!
  INFO root [0x0000113c] [2018-05-27 13:08:43,906] - Components::findComponents: find logger(1)...
  INFO root [0x0000113c] [2018-05-27 13:08:44,001] - Components::findComponents: found logger, addr:192.168.0.104:52292
  INFO root [0x0000113c] [2018-05-27 13:08:44,002] - Components::addComponent: reset orderLog, uid=24385!
  INFO root [0x0000113c] [2018-05-27 13:08:44,002] - Components::addComponent[logger], uid=24385, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000113c] [2018-05-27 13:08:44,005] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000113c] [2018-05-27 13:08:44,107] - Components::findComponents: found dbmgr, addr:192.168.0.104:52287
  INFO root [0x0000113c] [2018-05-27 13:08:44,107] - Components::addComponent: reset orderLog, uid=24385!
  INFO root [0x0000113c] [2018-05-27 13:08:44,108] - Components::addComponent[dbmgr], uid=24385, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000113c] [2018-05-27 13:08:44,109] - Components::findComponents: found dbmgr, addr:192.168.0.104:52287
  WARN root [0x0000113c] [2018-05-27 13:08:45,109] - Forwarding logs to logger[192.168.0.104:52292/0/0/0]...
 ERROR root [0x0000113c] [2018-05-27 13:10:34,872] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000113c] [2018-05-27 13:10:34,886] - The following logs sent to logger failed:
  WARN root [0x0000113c] [2018-05-27 13:10:34,886] - ==> [2018-05-27 13:10:34 870] TCPPacketReceiver::processPendingEvents(192.168.0.104:52292): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000113c] [2018-05-27 13:10:34,886] - ==> [2018-05-27 13:10:34 873] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000113c] [2018-05-27 13:10:34,942] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52287): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000113c] [2018-05-27 13:10:34,944] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000113c] [2018-05-27 13:10:34,958] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000113c] [2018-05-27 13:10:34,961] - onBaseAppShutDown: state=0
  INFO root [0x0000113c] [2018-05-27 13:10:34,961] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000113c] [2018-05-27 13:10:34,961] - onBaseAppShutDown: state=1
  INFO root [0x0000113c] [2018-05-27 13:10:34,961] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000113c] [2018-05-27 13:10:34,961] - onBaseAppShutDown: state=2
 ERROR root [0x0000113c] [2018-05-27 13:10:34,970] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x0000113c] [2018-05-27 13:10:34,970] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x0000113c] [2018-05-27 13:10:34,971] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x0000113c] [2018-05-27 13:10:34,971] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,972] - Account::~Account(): 2002
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,972] - Account::~Account(): 2004
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,972] - Room::~Room(): 2003
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,972] - Halls::~Halls(): 2001
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,973] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,973] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,973] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,973] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,973] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,973] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,974] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,974] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000113c] [2018-05-27 13:10:34,983] - Script::uninstall(): is successfully!
 DEBUG root [0x0000113c] [2018-05-27 13:10:34,984] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000014a0] [2018-05-27 13:10:36,196] - 
  INFO root [0x000014a0] [2018-05-27 13:10:36,197] - -----------------------------------------------------------------------------------------


  INFO root [0x000014a0] [2018-05-27 13:10:36,197] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x000014a0] [2018-05-27 13:10:36,197] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x000014a0] [2018-05-27 13:10:36,198] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x000014a0] [2018-05-27 13:10:36,200] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x000014a0] [2018-05-27 13:10:36,200] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x000014a0] [2018-05-27 13:10:36,201] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52345 )
  INFO root [0x000014a0] [2018-05-27 13:10:36,201] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52345, SOMAXCONN=128.
  INFO root [0x000014a0] [2018-05-27 13:10:36,201] - server-configs:
  INFO root [0x000014a0] [2018-05-27 13:10:36,201] - 	gameUpdateHertz : 10
  INFO root [0x000014a0] [2018-05-27 13:10:36,202] - 	entryScriptFile : kbemain
  INFO root [0x000014a0] [2018-05-27 13:10:36,202] - 	internalAddr : 192.168.0.104:52345
  INFO root [0x000014a0] [2018-05-27 13:10:36,202] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x000014a0] [2018-05-27 13:10:36,202] - 	componentID : 7001
  WARN root [0x000014a0] [2018-05-27 13:10:36,709] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20588, errorno=10048
  INFO root [0x000014a0] [2018-05-27 13:10:36,713] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 24783. PID: 14604 ----
  INFO root [0x000014a0] [2018-05-27 13:10:36,713] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x000014a0] [2018-05-27 13:10:36,713] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000014a0] [2018-05-27 13:10:36,714] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,837] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,837] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,837] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,840] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,841] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,841] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,841] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,870] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000014a0] [2018-05-27 13:10:36,904] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x000014a0] [2018-05-27 13:10:36,904] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,918] - loaded entity-script:Account(1).
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,919] - loaded entity-script:CheckName(2).
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,930] - loaded entity-script:Halls(3).
 DEBUG root [0x000014a0] [2018-05-27 13:10:36,931] - loaded entity-script:Room(4).
  INFO root [0x000014a0] [2018-05-27 13:10:36,931] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000014a0] [2018-05-27 13:10:36,931] - TelnetServer server is running on port 40000
  INFO root [0x000014a0] [2018-05-27 13:10:37,217] - ---- baseapp is running ----
 DEBUG root [0x000014a0] [2018-05-27 13:10:37,218] - Components::process(): Request for the process of identity...
  WARN root [0x000014a0] [2018-05-27 13:10:43,326] - EntityApp::checkTickPeriod: tick took 6109% (6.11 seconds)!
  INFO root [0x000014a0] [2018-05-27 13:10:44,398] - Components::findComponents: find logger(1)...
  INFO root [0x000014a0] [2018-05-27 13:10:44,444] - Components::findComponents: found logger, addr:192.168.0.104:52340
  INFO root [0x000014a0] [2018-05-27 13:10:44,444] - Components::addComponent: reset orderLog, uid=24783!
  INFO root [0x000014a0] [2018-05-27 13:10:44,444] - Components::addComponent[logger], uid=24783, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000014a0] [2018-05-27 13:10:44,445] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000014a0] [2018-05-27 13:10:44,549] - Components::findComponents: found dbmgr, addr:192.168.0.104:52344
  INFO root [0x000014a0] [2018-05-27 13:10:44,549] - Components::addComponent: reset orderLog, uid=24783!
  INFO root [0x000014a0] [2018-05-27 13:10:44,550] - Components::addComponent[dbmgr], uid=24783, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000014a0] [2018-05-27 13:10:44,551] - Components::findComponents: found dbmgr, addr:192.168.0.104:52344
  WARN root [0x000014a0] [2018-05-27 13:10:45,551] - Forwarding logs to logger[192.168.0.104:52340/0/0/0]...
 ERROR root [0x000014a0] [2018-05-27 13:13:45,515] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000014a0] [2018-05-27 13:13:45,529] - The following logs sent to logger failed:
  WARN root [0x000014a0] [2018-05-27 13:13:45,529] - ==> [2018-05-27 13:13:45 512] TCPPacketReceiver::processPendingEvents(192.168.0.104:52340): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000014a0] [2018-05-27 13:13:45,529] - ==> [2018-05-27 13:13:45 515] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000014a0] [2018-05-27 13:13:45,585] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52344): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000014a0] [2018-05-27 13:13:45,588] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000014a0] [2018-05-27 13:13:45,601] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000014a0] [2018-05-27 13:13:45,603] - onBaseAppShutDown: state=0
  INFO root [0x000014a0] [2018-05-27 13:13:45,603] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000014a0] [2018-05-27 13:13:45,603] - onBaseAppShutDown: state=1
  INFO root [0x000014a0] [2018-05-27 13:13:45,603] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000014a0] [2018-05-27 13:13:45,603] - onBaseAppShutDown: state=2
 ERROR root [0x000014a0] [2018-05-27 13:13:45,611] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000014a0] [2018-05-27 13:13:45,612] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000014a0] [2018-05-27 13:13:45,612] - Account::onCellWriteToDBCompleted(4): not found dbmgr!
 ERROR root [0x000014a0] [2018-05-27 13:13:45,613] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,613] - Account::~Account(): 2
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,613] - Account::~Account(): 4
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,613] - Room::~Room(): 3
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,613] - Halls::~Halls(): 1
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,614] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,614] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,614] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,615] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,615] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,615] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,615] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,615] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000014a0] [2018-05-27 13:13:45,625] - Script::uninstall(): is successfully!
 DEBUG root [0x000014a0] [2018-05-27 13:13:45,625] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000355c] [2018-05-27 13:13:46,844] - 
  INFO root [0x0000355c] [2018-05-27 13:13:46,844] - -----------------------------------------------------------------------------------------


  INFO root [0x0000355c] [2018-05-27 13:13:46,845] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x0000355c] [2018-05-27 13:13:46,845] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x0000355c] [2018-05-27 13:13:46,845] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x0000355c] [2018-05-27 13:13:46,847] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x0000355c] [2018-05-27 13:13:46,847] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x0000355c] [2018-05-27 13:13:46,849] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52400 )
  INFO root [0x0000355c] [2018-05-27 13:13:46,849] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52400, SOMAXCONN=128.
  INFO root [0x0000355c] [2018-05-27 13:13:46,849] - server-configs:
  INFO root [0x0000355c] [2018-05-27 13:13:46,849] - 	gameUpdateHertz : 10
  INFO root [0x0000355c] [2018-05-27 13:13:46,849] - 	entryScriptFile : kbemain
  INFO root [0x0000355c] [2018-05-27 13:13:46,850] - 	internalAddr : 192.168.0.104:52400
  INFO root [0x0000355c] [2018-05-27 13:13:46,850] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x0000355c] [2018-05-27 13:13:46,850] - 	componentID : 7001
  INFO root [0x0000355c] [2018-05-27 13:13:48,533] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 25407. PID: 14084 ----
  INFO root [0x0000355c] [2018-05-27 13:13:48,534] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x0000355c] [2018-05-27 13:13:48,534] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000355c] [2018-05-27 13:13:48,534] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,658] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,659] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,659] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,662] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,663] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,663] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,663] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,694] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000355c] [2018-05-27 13:13:48,724] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x0000355c] [2018-05-27 13:13:48,724] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,746] - loaded entity-script:Account(1).
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,747] - loaded entity-script:CheckName(2).
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,762] - loaded entity-script:Halls(3).
 DEBUG root [0x0000355c] [2018-05-27 13:13:48,764] - loaded entity-script:Room(4).
  INFO root [0x0000355c] [2018-05-27 13:13:48,764] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000355c] [2018-05-27 13:13:48,764] - TelnetServer server is running on port 40000
  INFO root [0x0000355c] [2018-05-27 13:13:49,090] - ---- baseapp is running ----
 DEBUG root [0x0000355c] [2018-05-27 13:13:49,090] - Components::process(): Request for the process of identity...
  WARN root [0x0000355c] [2018-05-27 13:13:49,400] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20250, errorno=10048
  WARN root [0x0000355c] [2018-05-27 13:13:55,511] - EntityApp::checkTickPeriod: tick took 6420% (6.42 seconds)!
  INFO root [0x0000355c] [2018-05-27 13:13:56,547] - Components::findComponents: find logger(1)...
  INFO root [0x0000355c] [2018-05-27 13:13:56,602] - Components::findComponents: found logger, addr:192.168.0.104:52399
  INFO root [0x0000355c] [2018-05-27 13:13:56,602] - Components::addComponent: reset orderLog, uid=25407!
  INFO root [0x0000355c] [2018-05-27 13:13:56,603] - Components::addComponent[logger], uid=25407, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000355c] [2018-05-27 13:13:56,605] - Components::findComponents: find dbmgr(2)...
  INFO root [0x0000355c] [2018-05-27 13:13:56,705] - Components::findComponents: found dbmgr, addr:192.168.0.104:52401
  INFO root [0x0000355c] [2018-05-27 13:13:56,705] - Components::addComponent: reset orderLog, uid=25407!
  INFO root [0x0000355c] [2018-05-27 13:13:56,705] - Components::addComponent[dbmgr], uid=25407, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000355c] [2018-05-27 13:13:56,705] - Components::findComponents: found dbmgr, addr:192.168.0.104:52401
  WARN root [0x0000355c] [2018-05-27 13:13:57,706] - Forwarding logs to logger[192.168.0.104:52399/0/0/0]...
 ERROR root [0x0000355c] [2018-05-27 13:20:00,952] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000355c] [2018-05-27 13:20:00,970] - The following logs sent to logger failed:
  WARN root [0x0000355c] [2018-05-27 13:20:00,970] - ==> [2018-05-27 13:20:00 949] TCPPacketReceiver::processPendingEvents(192.168.0.104:52399): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000355c] [2018-05-27 13:20:00,970] - ==> [2018-05-27 13:20:00 952] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000355c] [2018-05-27 13:20:01,022] - TCPPacketReceiver::processPendingEvents(192.168.0.104:52401): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000355c] [2018-05-27 13:20:01,025] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000355c] [2018-05-27 13:20:01,037] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000355c] [2018-05-27 13:20:01,039] - onBaseAppShutDown: state=0
  INFO root [0x0000355c] [2018-05-27 13:20:01,039] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000355c] [2018-05-27 13:20:01,039] - onBaseAppShutDown: state=1
  INFO root [0x0000355c] [2018-05-27 13:20:01,039] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000355c] [2018-05-27 13:20:01,040] - onBaseAppShutDown: state=2
 ERROR root [0x0000355c] [2018-05-27 13:20:01,047] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x0000355c] [2018-05-27 13:20:01,048] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x0000355c] [2018-05-27 13:20:01,048] - Account::onCellWriteToDBCompleted(2004): not found dbmgr!
 ERROR root [0x0000355c] [2018-05-27 13:20:01,049] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,049] - Account::~Account(): 2002
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,050] - Account::~Account(): 2004
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,050] - Room::~Room(): 2003
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,050] - Halls::~Halls(): 2001
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,051] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000355c] [2018-05-27 13:20:01,061] - Script::uninstall(): is successfully!
 DEBUG root [0x0000355c] [2018-05-27 13:20:01,061] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003b78] [2018-05-27 13:20:02,293] - 
  INFO root [0x00003b78] [2018-05-27 13:20:02,293] - -----------------------------------------------------------------------------------------


  INFO root [0x00003b78] [2018-05-27 13:20:02,294] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [0x00003b78] [2018-05-27 13:20:02,294] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [0x00003b78] [2018-05-27 13:20:02,294] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [0x00003b78] [2018-05-27 13:20:02,302] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:20015 )
  INFO root [0x00003b78] [2018-05-27 13:20:02,302] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.104:20015, SOMAXCONN=128.
  INFO root [0x00003b78] [2018-05-27 13:20:02,303] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:52485 )
  INFO root [0x00003b78] [2018-05-27 13:20:02,304] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:52485, SOMAXCONN=128.
  INFO root [0x00003b78] [2018-05-27 13:20:02,304] - server-configs:
  INFO root [0x00003b78] [2018-05-27 13:20:02,304] - 	gameUpdateHertz : 10
  INFO root [0x00003b78] [2018-05-27 13:20:02,304] - 	entryScriptFile : kbemain
  INFO root [0x00003b78] [2018-05-27 13:20:02,304] - 	internalAddr : 192.168.0.104:52485
  INFO root [0x00003b78] [2018-05-27 13:20:02,304] - 	externalAddr : 192.168.0.104:20015
  INFO root [0x00003b78] [2018-05-27 13:20:02,304] - 	componentID : 7001
  INFO root [0x00003b78] [2018-05-27 13:20:04,023] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 15:53:31 Apr 29 2018. AppID: 7001. UID: 26631. PID: 11820 ----
  INFO root [0x00003b78] [2018-05-27 13:20:04,024] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [0x00003b78] [2018-05-27 13:20:04,024] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003b78] [2018-05-27 13:20:04,024] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,148] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,148] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,148] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,152] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,153] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,153] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,154] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,189] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00003b78] [2018-05-27 13:20:04,223] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [0x00003b78] [2018-05-27 13:20:04,223] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,237] - loaded entity-script:Account(1).
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,238] - loaded entity-script:CheckName(2).
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,253] - loaded entity-script:Halls(3).
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,255] - loaded entity-script:Room(4).
  INFO root [0x00003b78] [2018-05-27 13:20:04,255] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003b78] [2018-05-27 13:20:04,255] - TelnetServer server is running on port 40000
  INFO root [0x00003b78] [2018-05-27 13:20:04,550] - ---- baseapp is running ----
 DEBUG root [0x00003b78] [2018-05-27 13:20:04,551] - Components::process(): Request for the process of identity...
  WARN root [0x00003b78] [2018-05-27 13:20:10,628] - EntityApp::checkTickPeriod: tick took 6077% (6.08 seconds)!
  INFO root [0x00003b78] [2018-05-27 13:20:11,651] - Components::findComponents: find logger(1)...
  INFO root [0x00003b78] [2018-05-27 13:20:11,662] - Components::findComponents: found logger, addr:192.168.0.104:52481
  INFO root [0x00003b78] [2018-05-27 13:20:11,662] - Components::addComponent: reset orderLog, uid=26631!
  INFO root [0x00003b78] [2018-05-27 13:20:11,663] - Components::addComponent[logger], uid=26631, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003b78] [2018-05-27 13:20:11,664] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003b78] [2018-05-27 13:20:11,766] - Components::findComponents: found dbmgr, addr:192.168.0.104:52478
  INFO root [0x00003b78] [2018-05-27 13:20:11,766] - Components::addComponent: reset orderLog, uid=26631!
  INFO root [0x00003b78] [2018-05-27 13:20:11,766] - Components::addComponent[dbmgr], uid=26631, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003b78] [2018-05-27 13:20:11,766] - Components::findComponents: found dbmgr, addr:192.168.0.104:52478
  WARN root [0x00003b78] [2018-05-27 13:20:12,767] - EntityApp::checkTickPeriod: tick took 1215% (1.22 seconds)!
  WARN root [0x00003b78] [2018-05-27 13:20:12,767] - Forwarding logs to logger[192.168.0.104:52481/0/0/0]...
