  INFO root [2018-06-03 12:32:49,908] - 
  INFO root [2018-06-03 12:32:49,956] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:32:50,967] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:32:50,969] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:32:50,969] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:32:51,338] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:32:51,365] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:32:51,370] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:63843 )
  INFO root [2018-06-03 12:32:51,371] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:63843, SOMAXCONN=128.
  INFO root [2018-06-03 12:32:51,371] - server-configs:
  INFO root [2018-06-03 12:32:51,372] - 	internalAddr : 192.168.0.103:63843
  INFO root [2018-06-03 12:32:51,372] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:32:51,372] - 	componentID : 9000
  INFO root [2018-06-03 12:32:53,411] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26277. PID: 11740 ----
  INFO root [2018-06-03 12:32:53,412] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:32:53,426] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:32:53,449] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:32:56,022] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:32:56,069] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:32:56,105] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:32:56,364] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:32:56,449] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:32:56,504] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:32:56,539] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:32:57,011] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:32:58,082] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:32:58,083] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:32:58,338] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:32:58,338] - TelnetServer server is running on port 31000
  WARN root [2018-06-03 12:32:58,338] - e:\kbengine\kbe\src\server\loginapp\loginapp.cpp:153: Profile scriptCall took 0.11 seconds
  INFO root [2018-06-03 12:32:58,912] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:32:58,949] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:33:06,293] - Components::findComponents: find logger(1)...
 ERROR root [2018-06-03 12:33:07,804] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-06-03 12:33:07,806] - Components::findComponents: receive error!
  WARN root [2018-06-03 12:33:07,807] - Components::findComponents: not found logger!
  INFO root [2018-06-03 12:33:08,813] - Components::findComponents: find dbmgr(1)...
  INFO root [2018-06-03 12:33:10,681] - 
  INFO root [2018-06-03 12:33:10,682] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:33:10,683] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:33:10,683] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:33:10,683] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:33:10,685] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:33:10,686] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:33:10,687] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:63853 )
  INFO root [2018-06-03 12:33:10,687] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:63853, SOMAXCONN=128.
  INFO root [2018-06-03 12:33:10,687] - server-configs:
  INFO root [2018-06-03 12:33:10,687] - 	internalAddr : 192.168.0.103:63853
  INFO root [2018-06-03 12:33:10,687] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:33:10,687] - 	componentID : 9000
  INFO root [2018-06-03 12:33:12,361] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26394. PID: 7660 ----
  INFO root [2018-06-03 12:33:12,361] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:33:12,362] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:33:12,362] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:33:12,483] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:33:12,484] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:33:12,484] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:33:12,487] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:33:12,487] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:33:12,487] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:33:12,488] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:33:12,514] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:33:12,541] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:33:12,541] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:33:12,543] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:33:12,543] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:33:12,836] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:33:12,836] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:33:19,964] - Components::findComponents: find logger(1)...
  WARN root [2018-06-03 12:33:21,063] - Components::findComponents: not found logger!
  INFO root [2018-06-03 12:33:22,084] - Components::findComponents: find dbmgr(1)...
  INFO root [2018-06-03 12:33:24,184] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:33:26,203] - Components::findComponents: find dbmgr(3)...
  INFO root [2018-06-03 12:33:28,223] - Components::findComponents: find dbmgr(4)...
  INFO root [2018-06-03 12:33:30,343] - Components::findComponents: find dbmgr(5)...
  INFO root [2018-06-03 12:33:32,463] - Components::findComponents: find dbmgr(6)...
  INFO root [2018-06-03 12:33:34,583] - Components::findComponents: find dbmgr(7)...
  INFO root [2018-06-03 12:33:36,703] - Components::findComponents: find dbmgr(8)...
  INFO root [2018-06-03 12:33:38,824] - Components::findComponents: find dbmgr(9)...
  WARN root [2018-06-03 12:33:39,135] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20802, errorno=10048
  INFO root [2018-06-03 12:33:40,144] - Components::findComponents: find dbmgr(10)...
  INFO root [2018-06-03 12:33:42,243] - Components::findComponents: find dbmgr(11)...
  INFO root [2018-06-03 12:33:44,263] - Components::findComponents: find dbmgr(12)...
  INFO root [2018-06-03 12:33:46,283] - Components::findComponents: find dbmgr(13)...
  INFO root [2018-06-03 12:33:48,303] - Components::findComponents: find dbmgr(14)...
  INFO root [2018-06-03 12:33:50,343] - Components::findComponents: find dbmgr(15)...
  INFO root [2018-06-03 12:33:52,443] - Components::findComponents: find dbmgr(16)...
  WARN root [2018-06-03 12:33:54,504] - Components::findComponents: find dbmgr(17)...
delay time is too long, please check the dbmgr logs!
  WARN root [2018-06-03 12:33:56,523] - Components::findComponents: find dbmgr(18)...
delay time is too long, please check the dbmgr logs!
  WARN root [2018-06-03 12:33:58,543] - Components::findComponents: find dbmgr(19)...
delay time is too long, please check the dbmgr logs!
  WARN root [2018-06-03 12:34:00,563] - Components::findComponents: find dbmgr(20)...
delay time is too long, please check the dbmgr logs!
  WARN root [2018-06-03 12:34:02,603] - Components::findComponents: find dbmgr(21)...
delay time is too long, please check the dbmgr logs!
  WARN root [2018-06-03 12:34:04,643] - Components::findComponents: find dbmgr(22)...
delay time is too long, please check the dbmgr logs!
  INFO root [2018-06-03 12:34:06,575] - 
  INFO root [2018-06-03 12:34:06,581] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:34:06,581] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:34:06,581] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:34:06,581] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:34:06,584] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:34:06,584] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:34:06,585] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:63894 )
  INFO root [2018-06-03 12:34:06,585] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:63894, SOMAXCONN=128.
  INFO root [2018-06-03 12:34:06,585] - server-configs:
  INFO root [2018-06-03 12:34:06,585] - 	internalAddr : 192.168.0.103:63894
  INFO root [2018-06-03 12:34:06,585] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:34:06,585] - 	componentID : 9000
  INFO root [2018-06-03 12:34:08,285] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26577. PID: 12520 ----
  INFO root [2018-06-03 12:34:08,286] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:34:08,286] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:34:08,286] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:34:08,410] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:34:08,410] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:34:08,411] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:34:08,414] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:34:08,415] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:34:08,415] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:34:08,415] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:34:08,444] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:34:08,477] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:34:08,477] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:34:08,479] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:34:08,480] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:34:08,813] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:34:08,813] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:34:11,622] - 
  INFO root [2018-06-03 12:34:11,623] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:34:11,623] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:34:11,623] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:34:11,624] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:34:11,626] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:34:11,626] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:34:11,628] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:63902 )
  INFO root [2018-06-03 12:34:11,628] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:63902, SOMAXCONN=128.
  INFO root [2018-06-03 12:34:11,628] - server-configs:
  INFO root [2018-06-03 12:34:11,628] - 	internalAddr : 192.168.0.103:63902
  INFO root [2018-06-03 12:34:11,629] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:34:11,629] - 	componentID : 9000
  INFO root [2018-06-03 12:34:13,308] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26593. PID: 12528 ----
  INFO root [2018-06-03 12:34:13,308] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:34:13,308] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:34:13,308] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:34:13,442] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:34:13,443] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:34:13,443] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:34:13,448] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:34:13,448] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:34:13,448] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:34:13,449] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:34:13,491] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:34:13,529] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:34:13,530] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:34:13,531] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:34:13,532] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:34:13,830] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:34:13,830] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:34:20,952] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 12:34:20,973] - Components::findComponents: found logger, addr:192.168.0.103:63899
  INFO root [2018-06-03 12:34:20,974] - Components::addComponent: reset orderLog, uid=26593!
  INFO root [2018-06-03 12:34:20,975] - Components::addComponent[logger], uid=26593, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:34:20,978] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:34:21,085] - Components::findComponents: found dbmgr, addr:192.168.0.103:63901
  INFO root [2018-06-03 12:34:21,086] - Components::addComponent: reset orderLog, uid=26593!
  INFO root [2018-06-03 12:34:21,087] - Components::addComponent[dbmgr], uid=26593, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:34:21,087] - Components::findComponents: found dbmgr, addr:192.168.0.103:63901
  WARN root [2018-06-03 12:34:22,087] - Forwarding logs to logger[192.168.0.103:63899/0/0/0]...
 ERROR root [2018-06-03 12:34:34,299] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:34:34,306] - The following logs sent to logger failed:
  WARN root [2018-06-03 12:34:34,307] - ==> [2018-06-03 12:34:34 299] TCPPacketReceiver::processPendingEvents(192.168.0.103:63899): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:34:34,307] - ==> [2018-06-03 12:34:34 300] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 12:34:34,354] - TCPPacketReceiver::processPendingEvents(192.168.0.103:63901): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:34:34,356] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:34:34,361] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 12:34:34,362] - onLoginAppShutDown()
  INFO root [2018-06-03 12:34:34,362] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 12:34:34,362] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 12:34:34,362] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:34:34,362] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:34:34,362] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:34:34,362] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:34:34,362] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:34:34,363] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:34:34,363] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:34:34,363] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:34:34,395] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 12:34:34,396] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 12:34:35,540] - 
  INFO root [2018-06-03 12:34:35,541] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:34:35,541] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:34:35,541] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:34:35,541] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:34:35,543] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:34:35,544] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:34:35,545] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:63938 )
  INFO root [2018-06-03 12:34:35,545] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:63938, SOMAXCONN=128.
  INFO root [2018-06-03 12:34:35,545] - server-configs:
  INFO root [2018-06-03 12:34:35,545] - 	internalAddr : 192.168.0.103:63938
  INFO root [2018-06-03 12:34:35,545] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:34:35,545] - 	componentID : 9000
  WARN root [2018-06-03 12:34:36,061] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20855, errorno=10048
  INFO root [2018-06-03 12:34:36,065] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26672. PID: 13080 ----
  INFO root [2018-06-03 12:34:36,065] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:34:36,065] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:34:36,066] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:34:36,190] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:34:36,191] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:34:36,191] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:34:36,194] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:34:36,194] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:34:36,195] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:34:36,195] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:34:36,223] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:34:36,250] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:34:36,250] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:34:36,252] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:34:36,252] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:34:36,528] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:34:36,528] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:34:43,632] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 12:34:43,721] - Components::findComponents: found logger, addr:192.168.0.103:63934
  INFO root [2018-06-03 12:34:43,722] - Components::addComponent: reset orderLog, uid=26672!
  INFO root [2018-06-03 12:34:43,723] - Components::addComponent[logger], uid=26672, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:34:43,725] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:34:43,826] - Components::findComponents: found dbmgr, addr:192.168.0.103:63937
  INFO root [2018-06-03 12:34:43,827] - Components::addComponent: reset orderLog, uid=26672!
  INFO root [2018-06-03 12:34:43,828] - Components::addComponent[dbmgr], uid=26672, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:34:43,828] - Components::findComponents: found dbmgr, addr:192.168.0.103:63937
  WARN root [2018-06-03 12:34:44,828] - Forwarding logs to logger[192.168.0.103:63934/0/0/0]...
 ERROR root [2018-06-03 12:38:22,173] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:38:22,179] - The following logs sent to logger failed:
  WARN root [2018-06-03 12:38:22,179] - ==> [2018-06-03 12:38:22 172] TCPPacketReceiver::processPendingEvents(192.168.0.103:63934): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:38:22,179] - ==> [2018-06-03 12:38:22 174] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 12:38:22,229] - TCPPacketReceiver::processPendingEvents(192.168.0.103:63937): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:38:22,230] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:38:22,234] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 12:38:22,235] - onLoginAppShutDown()
  INFO root [2018-06-03 12:38:22,235] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 12:38:22,235] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 12:38:22,235] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:38:22,235] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:38:22,235] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:38:22,235] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:38:22,235] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:38:22,235] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:38:22,236] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:38:22,236] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:38:22,244] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 12:38:22,244] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 12:38:23,330] - 
  INFO root [2018-06-03 12:38:23,330] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:38:23,330] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:38:23,331] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:38:23,331] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:38:23,333] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:38:23,333] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:38:23,334] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64047 )
  INFO root [2018-06-03 12:38:23,334] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64047, SOMAXCONN=128.
  INFO root [2018-06-03 12:38:23,334] - server-configs:
  INFO root [2018-06-03 12:38:23,335] - 	internalAddr : 192.168.0.103:64047
  INFO root [2018-06-03 12:38:23,335] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:38:23,335] - 	componentID : 9000
  INFO root [2018-06-03 12:38:25,043] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27413. PID: 12608 ----
  INFO root [2018-06-03 12:38:25,044] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:38:25,044] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:38:25,044] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:38:25,167] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:38:25,167] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:38:25,168] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:38:25,171] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:38:25,171] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:38:25,171] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:38:25,172] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:38:25,210] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:38:25,244] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:38:25,244] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:38:25,246] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:38:25,246] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:38:25,589] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:38:25,590] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:38:32,686] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 12:38:32,714] - Components::findComponents: found logger, addr:192.168.0.103:64054
  INFO root [2018-06-03 12:38:32,714] - Components::addComponent: reset orderLog, uid=27413!
  INFO root [2018-06-03 12:38:32,715] - Components::addComponent[logger], uid=27413, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:38:32,716] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:38:32,820] - Components::findComponents: found dbmgr, addr:192.168.0.103:64049
  INFO root [2018-06-03 12:38:32,821] - Components::addComponent: reset orderLog, uid=27413!
  INFO root [2018-06-03 12:38:32,821] - Components::addComponent[dbmgr], uid=27413, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:38:32,821] - Components::findComponents: found dbmgr, addr:192.168.0.103:64049
  WARN root [2018-06-03 12:38:33,822] - Forwarding logs to logger[192.168.0.103:64054/0/0/0]...
 ERROR root [2018-06-03 12:40:31,820] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:40:31,824] - The following logs sent to logger failed:
  WARN root [2018-06-03 12:40:31,824] - ==> [2018-06-03 12:40:31 818] TCPPacketReceiver::processPendingEvents(192.168.0.103:64054): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:40:31,824] - ==> [2018-06-03 12:40:31 821] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 12:40:31,872] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64049): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:40:31,874] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:40:31,877] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 12:40:31,878] - onLoginAppShutDown()
  INFO root [2018-06-03 12:40:31,878] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 12:40:31,878] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:40:31,879] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:40:31,887] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 12:40:31,887] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 12:40:33,020] - 
  INFO root [2018-06-03 12:40:33,021] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:40:33,021] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:40:33,022] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:40:33,022] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:40:33,024] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:40:33,024] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:40:33,025] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64096 )
  INFO root [2018-06-03 12:40:33,026] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64096, SOMAXCONN=128.
  INFO root [2018-06-03 12:40:33,026] - server-configs:
  INFO root [2018-06-03 12:40:33,026] - 	internalAddr : 192.168.0.103:64096
  INFO root [2018-06-03 12:40:33,026] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:40:33,026] - 	componentID : 9000
  WARN root [2018-06-03 12:40:33,567] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20674, errorno=10048
  INFO root [2018-06-03 12:40:33,571] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 27838. PID: 10784 ----
  INFO root [2018-06-03 12:40:33,571] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:40:33,571] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:40:33,572] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:40:33,696] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:40:33,696] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:40:33,697] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:40:33,700] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:40:33,700] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:40:33,700] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:40:33,701] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:40:33,727] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:40:33,754] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:40:33,754] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:40:33,756] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:40:33,756] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:40:34,025] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:40:34,026] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:40:41,123] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 12:40:41,210] - Components::findComponents: found logger, addr:192.168.0.103:64093
  INFO root [2018-06-03 12:40:41,211] - Components::addComponent: reset orderLog, uid=27838!
  INFO root [2018-06-03 12:40:41,211] - Components::addComponent[logger], uid=27838, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:40:41,213] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:40:41,316] - Components::findComponents: found dbmgr, addr:192.168.0.103:64089
  INFO root [2018-06-03 12:40:41,316] - Components::addComponent: reset orderLog, uid=27838!
  INFO root [2018-06-03 12:40:41,317] - Components::addComponent[dbmgr], uid=27838, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:40:41,317] - Components::findComponents: found dbmgr, addr:192.168.0.103:64089
  WARN root [2018-06-03 12:40:42,318] - Forwarding logs to logger[192.168.0.103:64093/0/0/0]...
 ERROR root [2018-06-03 12:42:54,598] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:42:54,599] - The following logs sent to logger failed:
  WARN root [2018-06-03 12:42:54,599] - ==> [2018-06-03 12:42:54 596] TCPPacketReceiver::processPendingEvents(192.168.0.103:64093): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:42:54,599] - ==> [2018-06-03 12:42:54 598] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 12:42:54,655] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64089): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:42:54,656] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:42:54,661] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 12:42:54,662] - onLoginAppShutDown()
  INFO root [2018-06-03 12:42:54,662] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 12:42:54,662] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 12:42:54,662] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:42:54,663] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:42:54,663] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:42:54,663] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:42:54,663] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:42:54,663] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:42:54,663] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:42:54,663] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:42:54,671] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 12:42:54,671] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 12:42:55,804] - 
  INFO root [2018-06-03 12:42:55,810] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:42:55,810] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:42:55,810] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:42:55,810] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:42:55,813] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:42:55,814] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:42:55,815] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64163 )
  INFO root [2018-06-03 12:42:55,816] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64163, SOMAXCONN=128.
  INFO root [2018-06-03 12:42:55,816] - server-configs:
  INFO root [2018-06-03 12:42:55,816] - 	internalAddr : 192.168.0.103:64163
  INFO root [2018-06-03 12:42:55,816] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:42:55,816] - 	componentID : 9000
  INFO root [2018-06-03 12:42:57,548] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 28305. PID: 12632 ----
  INFO root [2018-06-03 12:42:57,549] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:42:57,549] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:42:57,549] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:42:57,674] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:42:57,674] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:42:57,674] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:42:57,677] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:42:57,678] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:42:57,678] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:42:57,678] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:42:57,710] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:42:57,742] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:42:57,742] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:42:57,743] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:42:57,744] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:42:58,029] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:42:58,029] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:43:05,164] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 12:43:05,199] - Components::findComponents: found logger, addr:192.168.0.103:64161
  INFO root [2018-06-03 12:43:05,200] - Components::addComponent: reset orderLog, uid=28305!
  INFO root [2018-06-03 12:43:05,201] - Components::addComponent[logger], uid=28305, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:43:05,202] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:43:05,306] - Components::findComponents: found dbmgr, addr:192.168.0.103:64166
  INFO root [2018-06-03 12:43:05,306] - Components::addComponent: reset orderLog, uid=28305!
  INFO root [2018-06-03 12:43:05,307] - Components::addComponent[dbmgr], uid=28305, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:43:05,307] - Components::findComponents: found dbmgr, addr:192.168.0.103:64166
  WARN root [2018-06-03 12:43:06,308] - Forwarding logs to logger[192.168.0.103:64161/0/0/0]...
 ERROR root [2018-06-03 12:45:27,975] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:45:27,976] - The following logs sent to logger failed:
  WARN root [2018-06-03 12:45:27,976] - ==> [2018-06-03 12:45:27 973] TCPPacketReceiver::processPendingEvents(192.168.0.103:64161): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:45:27,976] - ==> [2018-06-03 12:45:27 976] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 12:45:28,031] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64166): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:45:28,034] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:45:28,036] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 12:45:28,039] - onLoginAppShutDown()
  INFO root [2018-06-03 12:45:28,039] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 12:45:28,039] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 12:45:28,039] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:45:28,039] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:45:28,040] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:45:28,040] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:45:28,040] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:45:28,040] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:45:28,040] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:45:28,040] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:45:28,048] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 12:45:28,048] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 12:45:29,205] - 
  INFO root [2018-06-03 12:45:29,205] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:45:29,206] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:45:29,206] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:45:29,206] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:45:29,218] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:45:29,218] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:45:29,221] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64225 )
  INFO root [2018-06-03 12:45:29,221] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64225, SOMAXCONN=128.
  INFO root [2018-06-03 12:45:29,222] - server-configs:
  INFO root [2018-06-03 12:45:29,222] - 	internalAddr : 192.168.0.103:64225
  INFO root [2018-06-03 12:45:29,222] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:45:29,222] - 	componentID : 9000
  INFO root [2018-06-03 12:45:30,994] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 28804. PID: 12044 ----
  INFO root [2018-06-03 12:45:30,994] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:45:30,995] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:45:30,995] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:45:31,126] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:45:31,127] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:45:31,127] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:45:31,130] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:45:31,130] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:45:31,131] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:45:31,131] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:45:31,164] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:45:31,198] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:45:31,198] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:45:31,200] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:45:31,200] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:45:31,535] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:45:31,535] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:45:38,601] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 12:45:38,687] - Components::findComponents: found logger, addr:192.168.0.103:64224
  INFO root [2018-06-03 12:45:38,688] - Components::addComponent: reset orderLog, uid=28804!
  INFO root [2018-06-03 12:45:38,688] - Components::addComponent[logger], uid=28804, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:45:38,689] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:45:38,790] - Components::findComponents: found dbmgr, addr:192.168.0.103:64219
  INFO root [2018-06-03 12:45:38,790] - Components::addComponent: reset orderLog, uid=28804!
  INFO root [2018-06-03 12:45:38,790] - Components::addComponent[dbmgr], uid=28804, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:45:38,790] - Components::findComponents: found dbmgr, addr:192.168.0.103:64219
  WARN root [2018-06-03 12:45:39,790] - Forwarding logs to logger[192.168.0.103:64224/0/0/0]...
 ERROR root [2018-06-03 12:46:59,777] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:46:59,781] - The following logs sent to logger failed:
  WARN root [2018-06-03 12:46:59,782] - ==> [2018-06-03 12:46:59 776] TCPPacketReceiver::processPendingEvents(192.168.0.103:64224): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:46:59,782] - ==> [2018-06-03 12:46:59 778] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 12:46:59,834] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64219): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 12:46:59,836] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 12:46:59,837] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 12:46:59,839] - onLoginAppShutDown()
  INFO root [2018-06-03 12:46:59,840] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 12:46:59,840] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 12:46:59,840] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:46:59,840] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:46:59,840] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:46:59,840] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:46:59,840] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:46:59,840] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:46:59,840] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:46:59,841] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:46:59,848] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 12:46:59,848] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 12:47:00,998] - 
  INFO root [2018-06-03 12:47:00,999] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 12:47:01,000] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 12:47:01,000] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 12:47:01,000] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 12:47:01,003] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 12:47:01,003] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 12:47:01,005] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64274 )
  INFO root [2018-06-03 12:47:01,005] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64274, SOMAXCONN=128.
  INFO root [2018-06-03 12:47:01,005] - server-configs:
  INFO root [2018-06-03 12:47:01,005] - 	internalAddr : 192.168.0.103:64274
  INFO root [2018-06-03 12:47:01,006] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 12:47:01,006] - 	componentID : 9000
  INFO root [2018-06-03 12:47:02,749] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 29105. PID: 9684 ----
  INFO root [2018-06-03 12:47:02,750] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 12:47:02,750] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 12:47:02,751] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 12:47:02,878] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 12:47:02,879] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 12:47:02,879] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 12:47:02,882] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 12:47:02,882] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 12:47:02,882] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 12:47:02,883] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 12:47:02,915] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 12:47:02,951] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 12:47:02,951] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 12:47:02,954] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 12:47:02,954] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 12:47:03,259] - ---- loginapp is running ----
 DEBUG root [2018-06-03 12:47:03,259] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 12:47:10,314] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 12:47:10,390] - Components::findComponents: found logger, addr:192.168.0.103:64273
  INFO root [2018-06-03 12:47:10,391] - Components::addComponent: reset orderLog, uid=29105!
  INFO root [2018-06-03 12:47:10,391] - Components::addComponent[logger], uid=29105, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:47:10,392] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 12:47:10,492] - Components::findComponents: found dbmgr, addr:192.168.0.103:64268
  INFO root [2018-06-03 12:47:10,492] - Components::addComponent: reset orderLog, uid=29105!
  INFO root [2018-06-03 12:47:10,492] - Components::addComponent[dbmgr], uid=29105, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 12:47:10,493] - Components::findComponents: found dbmgr, addr:192.168.0.103:64268
  WARN root [2018-06-03 12:47:11,493] - Forwarding logs to logger[192.168.0.103:64273/0/0/0]...
 ERROR root [2018-06-03 13:27:43,143] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:27:43,146] - The following logs sent to logger failed:
  WARN root [2018-06-03 13:27:43,146] - ==> [2018-06-03 13:27:43 139] TCPPacketReceiver::processPendingEvents(192.168.0.103:64273): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:27:43,146] - ==> [2018-06-03 13:27:43 144] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 13:27:43,217] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64268): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:27:43,218] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:27:43,224] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 13:27:43,224] - onLoginAppShutDown()
  INFO root [2018-06-03 13:27:43,225] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 13:27:43,225] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 13:27:43,225] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:27:43,225] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:27:43,225] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:27:43,225] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:27:43,225] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:27:43,225] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:27:43,225] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:27:43,226] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:27:43,234] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 13:27:43,234] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 13:27:44,470] - 
  INFO root [2018-06-03 13:27:44,471] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 13:27:44,471] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 13:27:44,471] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 13:27:44,471] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 13:27:44,474] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 13:27:44,475] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 13:27:44,476] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64675 )
  INFO root [2018-06-03 13:27:44,476] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64675, SOMAXCONN=128.
  INFO root [2018-06-03 13:27:44,477] - server-configs:
  INFO root [2018-06-03 13:27:44,477] - 	internalAddr : 192.168.0.103:64675
  INFO root [2018-06-03 13:27:44,477] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 13:27:44,477] - 	componentID : 9000
  INFO root [2018-06-03 13:27:44,894] - Components::findLogger: found logger, addr:192.168.0.103:64672
  INFO root [2018-06-03 13:27:44,894] - Components::addComponent: reset orderLog, uid=4314!
  INFO root [2018-06-03 13:27:44,895] - Components::addComponent[logger], uid=4314, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:27:44,901] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 4314. PID: 18284 ----
  INFO root [2018-06-03 13:27:44,902] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 13:27:44,902] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 13:27:44,902] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 13:27:45,027] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:27:45,028] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:27:45,028] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:27:45,031] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:27:45,031] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:27:45,031] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:27:45,032] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:27:45,060] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:27:45,089] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 13:27:45,090] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 13:27:45,091] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 13:27:45,091] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 13:27:45,391] - ---- loginapp is running ----
 DEBUG root [2018-06-03 13:27:45,391] - Components::process(): Request for the process of identity...
  WARN root [2018-06-03 13:27:51,458] - Forwarding logs to logger[192.168.0.103:64672/0/0/0]...
 ERROR root [2018-06-03 13:44:42,764] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:44:42,765] - The following logs sent to logger failed:
  WARN root [2018-06-03 13:44:42,765] - ==> [2018-06-03 13:44:42 758] TCPPacketReceiver::processPendingEvents(192.168.0.103:64672): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:44:42,765] - ==> [2018-06-03 13:44:42 764] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 13:44:42,828] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64670): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:44:42,830] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:44:42,834] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 13:44:42,835] - onLoginAppShutDown()
  INFO root [2018-06-03 13:44:42,835] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 13:44:42,835] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 13:44:42,835] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:44:42,836] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:44:42,836] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:44:42,836] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:44:42,836] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:44:42,836] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:44:42,836] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:44:42,836] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:44:42,844] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 13:44:42,845] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 13:44:44,082] - 
  INFO root [2018-06-03 13:44:44,084] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 13:44:44,084] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 13:44:44,084] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 13:44:44,084] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 13:44:44,094] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 13:44:44,094] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 13:44:44,099] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64858 )
  INFO root [2018-06-03 13:44:44,099] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64858, SOMAXCONN=128.
  INFO root [2018-06-03 13:44:44,099] - server-configs:
  INFO root [2018-06-03 13:44:44,100] - 	internalAddr : 192.168.0.103:64858
  INFO root [2018-06-03 13:44:44,100] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 13:44:44,100] - 	componentID : 9000
  INFO root [2018-06-03 13:44:45,849] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 7645. PID: 17284 ----
  INFO root [2018-06-03 13:44:45,850] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 13:44:45,850] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 13:44:45,850] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 13:44:45,985] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:44:45,986] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:44:45,986] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:44:45,990] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:44:45,991] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:44:45,991] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:44:45,991] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:44:46,026] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:44:46,056] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 13:44:46,056] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 13:44:46,058] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 13:44:46,058] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 13:44:46,359] - ---- loginapp is running ----
 DEBUG root [2018-06-03 13:44:46,359] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 13:44:53,459] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 13:44:53,510] - Components::findComponents: found logger, addr:192.168.0.103:64860
  INFO root [2018-06-03 13:44:53,510] - Components::addComponent: reset orderLog, uid=7645!
  INFO root [2018-06-03 13:44:53,510] - Components::addComponent[logger], uid=7645, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:44:53,511] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 13:44:53,617] - Components::findComponents: found dbmgr, addr:192.168.0.103:64853
  INFO root [2018-06-03 13:44:53,617] - Components::addComponent: reset orderLog, uid=7645!
  INFO root [2018-06-03 13:44:53,618] - Components::addComponent[dbmgr], uid=7645, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:44:53,618] - Components::findComponents: found dbmgr, addr:192.168.0.103:64853
  WARN root [2018-06-03 13:44:54,618] - Forwarding logs to logger[192.168.0.103:64860/0/0/0]...
 ERROR root [2018-06-03 13:46:27,352] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:46:27,360] - The following logs sent to logger failed:
  WARN root [2018-06-03 13:46:27,361] - ==> [2018-06-03 13:46:27 351] TCPPacketReceiver::processPendingEvents(192.168.0.103:64860): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:46:27,361] - ==> [2018-06-03 13:46:27 353] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 13:46:27,418] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64853): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:46:27,420] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:46:27,424] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 13:46:27,428] - onLoginAppShutDown()
  INFO root [2018-06-03 13:46:27,428] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 13:46:27,428] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 13:46:27,428] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:46:27,429] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:46:27,429] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:46:27,429] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:46:27,429] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:46:27,429] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:46:27,429] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:46:27,429] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:46:27,437] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 13:46:27,437] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 13:46:28,687] - 
  INFO root [2018-06-03 13:46:28,687] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 13:46:28,688] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 13:46:28,688] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 13:46:28,688] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 13:46:28,692] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 13:46:28,693] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 13:46:28,697] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64904 )
  INFO root [2018-06-03 13:46:28,697] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64904, SOMAXCONN=128.
  INFO root [2018-06-03 13:46:28,697] - server-configs:
  INFO root [2018-06-03 13:46:28,697] - 	internalAddr : 192.168.0.103:64904
  INFO root [2018-06-03 13:46:28,697] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 13:46:28,697] - 	componentID : 9000
  WARN root [2018-06-03 13:46:29,194] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20486, errorno=10048
  INFO root [2018-06-03 13:46:29,197] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 7988. PID: 16772 ----
  INFO root [2018-06-03 13:46:29,200] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 13:46:29,200] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 13:46:29,200] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 13:46:29,330] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:46:29,330] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:46:29,330] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:46:29,334] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:46:29,334] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:46:29,334] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:46:29,334] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:46:29,365] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:46:29,395] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 13:46:29,395] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 13:46:29,397] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 13:46:29,398] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 13:46:29,689] - ---- loginapp is running ----
 DEBUG root [2018-06-03 13:46:29,690] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 13:46:36,790] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 13:46:36,895] - Components::findComponents: found logger, addr:192.168.0.103:64900
  INFO root [2018-06-03 13:46:36,895] - Components::addComponent: reset orderLog, uid=7988!
  INFO root [2018-06-03 13:46:36,896] - Components::addComponent[logger], uid=7988, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:46:36,897] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 13:46:37,001] - Components::findComponents: found dbmgr, addr:192.168.0.103:64905
  INFO root [2018-06-03 13:46:37,002] - Components::addComponent: reset orderLog, uid=7988!
  INFO root [2018-06-03 13:46:37,002] - Components::addComponent[dbmgr], uid=7988, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:46:37,003] - Components::findComponents: found dbmgr, addr:192.168.0.103:64905
  WARN root [2018-06-03 13:46:38,003] - Forwarding logs to logger[192.168.0.103:64900/0/0/0]...
 ERROR root [2018-06-03 13:47:24,220] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:47:24,229] - The following logs sent to logger failed:
  WARN root [2018-06-03 13:47:24,229] - ==> [2018-06-03 13:47:24 219] TCPPacketReceiver::processPendingEvents(192.168.0.103:64900): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:47:24,230] - ==> [2018-06-03 13:47:24 221] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 13:47:24,285] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64905): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:47:24,290] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:47:24,297] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 13:47:24,298] - onLoginAppShutDown()
  INFO root [2018-06-03 13:47:24,298] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 13:47:24,298] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 13:47:24,298] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:47:24,299] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:47:24,299] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:47:24,299] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:47:24,299] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:47:24,299] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:47:24,299] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:47:24,299] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:47:24,307] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 13:47:24,307] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 13:47:25,549] - 
  INFO root [2018-06-03 13:47:25,550] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 13:47:25,551] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 13:47:25,551] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 13:47:25,551] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 13:47:25,555] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 13:47:25,555] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 13:47:25,557] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:64951 )
  INFO root [2018-06-03 13:47:25,557] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:64951, SOMAXCONN=128.
  INFO root [2018-06-03 13:47:25,557] - server-configs:
  INFO root [2018-06-03 13:47:25,557] - 	internalAddr : 192.168.0.103:64951
  INFO root [2018-06-03 13:47:25,557] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 13:47:25,557] - 	componentID : 9000
  WARN root [2018-06-03 13:47:26,070] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20618, errorno=10048
  INFO root [2018-06-03 13:47:26,074] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 8174. PID: 17860 ----
  INFO root [2018-06-03 13:47:26,074] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 13:47:26,075] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 13:47:26,075] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 13:47:26,198] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:47:26,198] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:47:26,198] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:47:26,201] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:47:26,202] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:47:26,202] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:47:26,202] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:47:26,231] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:47:26,259] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 13:47:26,259] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 13:47:26,261] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 13:47:26,261] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 13:47:26,536] - ---- loginapp is running ----
 DEBUG root [2018-06-03 13:47:26,536] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 13:47:33,641] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 13:47:33,656] - Components::findComponents: found logger, addr:192.168.0.103:64948
  INFO root [2018-06-03 13:47:33,656] - Components::addComponent: reset orderLog, uid=8174!
  INFO root [2018-06-03 13:47:33,656] - Components::addComponent[logger], uid=8174, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:47:33,657] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 13:47:33,761] - Components::findComponents: found dbmgr, addr:192.168.0.103:64946
  INFO root [2018-06-03 13:47:33,762] - Components::addComponent: reset orderLog, uid=8174!
  INFO root [2018-06-03 13:47:33,763] - Components::addComponent[dbmgr], uid=8174, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:47:33,763] - Components::findComponents: found dbmgr, addr:192.168.0.103:64946
  WARN root [2018-06-03 13:47:34,764] - Forwarding logs to logger[192.168.0.103:64948/0/0/0]...
 ERROR root [2018-06-03 13:49:21,714] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:49:21,722] - The following logs sent to logger failed:
  WARN root [2018-06-03 13:49:21,722] - ==> [2018-06-03 13:49:21 711] TCPPacketReceiver::processPendingEvents(192.168.0.103:64948): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:49:21,722] - ==> [2018-06-03 13:49:21 714] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-06-03 13:49:21,779] - TCPPacketReceiver::processPendingEvents(192.168.0.103:64946): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-06-03 13:49:21,783] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-06-03 13:49:21,788] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-06-03 13:49:21,790] - onLoginAppShutDown()
  INFO root [2018-06-03 13:49:21,790] - Shutdowner::onShutdown: shutting down
  INFO root [2018-06-03 13:49:21,790] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-06-03 13:49:21,790] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:49:21,790] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:49:21,790] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:49:21,790] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:49:21,791] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:49:21,791] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:49:21,791] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:49:21,791] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:49:21,798] - Script::uninstall(): is successfully!
 DEBUG root [2018-06-03 13:49:21,798] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-06-03 13:49:23,045] - 
  INFO root [2018-06-03 13:49:23,047] - -----------------------------------------------------------------------------------------


  INFO root [2018-06-03 13:49:23,048] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-06-03 13:49:23,048] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-06-03 13:49:23,048] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-06-03 13:49:23,051] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:20013 )
  INFO root [2018-06-03 13:49:23,052] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.103:20013, SOMAXCONN=128.
  INFO root [2018-06-03 13:49:23,054] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.103 ( 192.168.0.103:65012 )
  INFO root [2018-06-03 13:49:23,054] - NetworkInterface::initialize(INTERNAL): address 192.168.0.103:65012, SOMAXCONN=128.
  INFO root [2018-06-03 13:49:23,054] - server-configs:
  INFO root [2018-06-03 13:49:23,055] - 	internalAddr : 192.168.0.103:65012
  INFO root [2018-06-03 13:49:23,055] - 	externalAddr : 192.168.0.103:20013
  INFO root [2018-06-03 13:49:23,055] - 	componentID : 9000
  INFO root [2018-06-03 13:49:24,775] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 8556. PID: 19116 ----
  INFO root [2018-06-03 13:49:24,776] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-06-03 13:49:24,776] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-06-03 13:49:24,776] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-06-03 13:49:24,899] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-06-03 13:49:24,899] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-06-03 13:49:24,900] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-06-03 13:49:24,903] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-06-03 13:49:24,903] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-06-03 13:49:24,903] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-06-03 13:49:24,903] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-06-03 13:49:24,934] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-06-03 13:49:24,965] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-06-03 13:49:24,965] - Script::install(): KBExtra is successfully!
S_INFO root [2018-06-03 13:49:24,967] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-06-03 13:49:24,967] - TelnetServer server is running on port 31000
  INFO root [2018-06-03 13:49:25,252] - ---- loginapp is running ----
 DEBUG root [2018-06-03 13:49:25,252] - Components::process(): Request for the process of identity...
  INFO root [2018-06-03 13:49:32,347] - Components::findComponents: find logger(1)...
  INFO root [2018-06-03 13:49:32,440] - Components::findComponents: found logger, addr:192.168.0.103:65008
  INFO root [2018-06-03 13:49:32,441] - Components::addComponent: reset orderLog, uid=8556!
  INFO root [2018-06-03 13:49:32,441] - Components::addComponent[logger], uid=8556, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:49:32,442] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-06-03 13:49:32,548] - Components::findComponents: found dbmgr, addr:192.168.0.103:65013
  INFO root [2018-06-03 13:49:32,548] - Components::addComponent: reset orderLog, uid=8556!
  INFO root [2018-06-03 13:49:32,549] - Components::addComponent[dbmgr], uid=8556, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-06-03 13:49:32,549] - Components::findComponents: found dbmgr, addr:192.168.0.103:65013
  WARN root [2018-06-03 13:49:33,549] - Forwarding logs to logger[192.168.0.103:65008/0/0/0]...
